import * as THREE from 'three/webgpu';
import {windowCat} from './cat.js';
import {milestoneRecorder} from './milestone-recorder.js';

// Isolated mechanical/look-development route. It never changes the player's main-room camera.
const canvas=document.querySelector('#cat-study'),diagnostics=document.querySelector('#study-diagnostics'),error=document.querySelector('#study-error');
addEventListener('error',e=>{error.textContent=String(e.error?.stack||e.message)});addEventListener('unhandledrejection',e=>{error.textContent=String(e.reason?.stack||e.reason)});
const scene=new THREE.Scene();scene.background=new THREE.Color('#fffaf5');
const renderer=new THREE.WebGPURenderer({canvas,antialias:true,forceWebGL:new URLSearchParams(location.search).has('webgl')});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const camera=new THREE.PerspectiveCamera(35,innerWidth/innerHeight,.025,20),target=new THREE.Vector3(0,.90,-.02);
const room={root:new THREE.Group()};scene.add(room.root);room.root.scale.setScalar(.75);const cat=windowCat(room);cat.root.position.set(0,.88,0);
const key=new THREE.DirectionalLight('#fff2dd',2.4);key.position.set(-2,4,3);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-2;key.shadow.camera.right=2;key.shadow.camera.top=2;key.shadow.camera.bottom=-2;scene.add(key);
scene.add(new THREE.HemisphereLight('#fbf4e9','#c5b4a7',1.15));const rim=new THREE.DirectionalLight('#eadfff',.6);rim.position.set(2,2,-3);scene.add(rim);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(8,8),new THREE.MeshStandardNodeMaterial({color:'#f2e7d7',roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const sill=new THREE.Mesh(new THREE.BoxGeometry(.46,.045,1.45),new THREE.MeshStandardNodeMaterial({color:'#dfc5a9',roughness:.89}));sill.position.set(0,.638,0);sill.receiveShadow=true;scene.add(sill);
cat.setWorld({floorFree(x,z){return x>-.9&&x<2.0&&z>-1.5&&z<1.5},supportHeight(){return 0}},{camera,isLive:()=>false});
let mode='rest',view='hero',mapStripped=true,stepClock=0,last=performance.now(),frame=0,playing=false,selected='',evidence=false,disposed=false;
const materials=new Map(),neutral=new THREE.MeshStandardNodeMaterial({color:'#ece1d3',roughness:.85});
const originalVisibility=new Map();cat.root.traverse(o=>{if(o.isMesh){materials.set(o,o.material);originalVisibility.set(o,o.visible)}});
function stripped(enabled){mapStripped=enabled;cat.root.traverse(o=>{if(!o.isMesh||o.name.endsWith('Solid')||/Solid\d$/.test(o.name))return;const detail=/Eye|Nose|Whisker|Mouth|Canine|Tongue|crease/i.test(o.name);if(o.material?.side===THREE.BackSide){o.visible=!enabled;return}o.material=enabled?neutral:materials.get(o);o.visible=enabled?!detail:originalVisibility.get(o)})}
const views={hero:[.83,.36,1.20],front:[0,.32,1.50],right:[1.50,.32,0],rear:[0,.35,-1.50],left:[-1.50,.32,0],orbitPlus:[.98,.36,1.18],orbitMinus:[-.98,.36,1.18],head:[.46,.20,.66]};
function setView(id){view=id;const p=views[id];camera.position.copy(target).add(new THREE.Vector3(...p));camera.lookAt(target);}
function reset(){const m=cat.locomotion;Object.assign(m,{phase:'sill-idle',age:0,time:0,next:10000,position:{...m.home},heading:0,speed:0,standing:0,route:[],velocity:{x:0,y:0,z:0}});cat.root.position.set(0,.88,0);cat.root.rotation.set(0,0,0);stepClock=0;}
function advance(dt){cat.update(dt,camera);stepClock+=dt;}
function staticPose(id){reset();mode=id;playing=false;if(id==='stand'){cat.locomotion.phase='floor-idle';cat.locomotion.standing=1;cat.locomotion.position.y=0;cat.update(0,camera)}else if(id==='walk'){cat.locomotion.phase='walking';cat.locomotion.standing=1;cat.locomotion.position={x:.45,y:0,z:0};cat.locomotion.route=[{x:.45,z:1.2}];cat.locomotion.heading=0;cat.locomotion.walkSpeed=.32;for(let i=0;i<60;i++)advance(1/60)}else if(id==='jump-down'||id==='jump-up'){cat.explore();let safety=0;while(cat.locomotion.phase!=='jump-down'&&safety++<300)advance(1/60);if(id==='jump-up'){while(cat.locomotion.airborne&&safety++<600)advance(1/60);cat.locomotion.position={...cat.locomotion.landingSpot()};cat.locomotion.heading=-Math.PI/2;cat.locomotion.beginJump(true)}let duration=cat.locomotion.jump.duration;for(let i=0;i<Math.floor(duration*.53*60);i++)advance(1/60)}else{cat.update(0,camera)};cat.root.getObjectByName('CatHead').rotation.set(0,0,0);const position=cat.root.getWorldPosition(new THREE.Vector3());target.copy(position).add(new THREE.Vector3(0,id==='rest'?.25:.34,0));setView(view);stripped(mapStripped);}
function button(label,fn){const b=document.createElement('button');b.textContent=label;b.addEventListener('click',()=>{fn();refresh()});document.querySelector('nav').append(b);return b}
for(const id of Object.keys(views))button('View '+id,()=>setView(id));
for(const id of ['rest','stand','walk','jump-down','jump-up'])button('Pose '+id,()=>staticPose(id));
button('Animate roaming',()=>{reset();mode='roaming';playing=true;cat.explore();stripped(mapStripped)});button('Pause',()=>playing=false);button('Step 0.5 sec',()=>{for(let i=0;i<30;i++)advance(1/60)});button('Call back to sill',()=>{cat.recall();playing=true;mode='roaming'});button('Neutral blockout',()=>stripped(true));button('ToonLab beauty',()=>stripped(false));
button('Yawn study',()=>{staticPose('rest');cat.yawn();for(let i=0;i<85;i++)advance(1/60);cat.root.getObjectByName('CatHead').rotation.set(-.20,0,0);stripped(false);mode='yawn'});
button('Grazing light',()=>{key.position.set(-2,.65,1);key.intensity=2.3});button('Neutral light',()=>{key.position.set(-2,4,3);key.intensity=2.4});
button('Evidence frame',()=>{evidence=true;document.querySelector('nav').hidden=true;document.querySelector('aside').hidden=true;ground.visible=false;sill.visible=false;scene.background.set('#ffffff');canvas.style.width=Math.min(innerWidth,innerHeight)+'px';canvas.style.height=canvas.style.width;canvas.style.margin='0 auto';camera.aspect=1;camera.updateProjectionMatrix();renderer.setSize(Math.min(innerWidth,innerHeight),Math.min(innerWidth,innerHeight),false);target.copy(cat.root.getWorldPosition(new THREE.Vector3())).add(new THREE.Vector3(0,mode==='rest'?.167:.22,-.02));camera.position.copy(target).add(new THREE.Vector3(...views[view]).multiplyScalar(.48));camera.lookAt(target);});
button('Black silhouette',()=>{stripped(true);neutral.color.set('#000000');neutral.roughness=1;renderer.toneMapping=THREE.NoToneMapping;renderer.toneMappingExposure=1});
button('Exploded assembly',()=>{playing=false;cat.setExploded(true)});button('Assembled cat',()=>cat.setExploded(false));
addEventListener('keydown',e=>{if(e.key!=='Escape'||!evidence)return;evidence=false;document.querySelector('nav').hidden=false;document.querySelector('aside').hidden=false;ground.visible=true;sill.visible=true;scene.background.set('#fffaf5');canvas.style.width='100%';canvas.style.height='100%';canvas.style.margin='0';renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();neutral.color.set('#ece1d3');renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05});
function refresh(){diagnostics.textContent=JSON.stringify({ready:frame>0,backend:renderer.backend?.isWebGPUBackend?'WebGPU':'WebGL2',view,pose:mode,phase:cat.state.phase,time:+stepClock.toFixed(3),frames:frame,stripped:mapStripped,joints:cat.rig.skeleton.bones.length,maxReachError:cat.rig.maxReachError,earRootClosest:Math.max(...cat.earSocketChecks),selected},null,2)}
const recorder=milestoneRecorder(canvas,()=>({backend:renderer.backend?.isWebGPUBackend?'WebGPU':'WebGL2',mode:'cat-study-'+view+'-'+mode+(mapStripped?'-neutral':'-toon'),lighting:key.position.y<1?'grazing':'neutral-studio',cat:{phase:cat.state.phase,age:cat.locomotion?.age,visits:cat.state.visits,eyesClosed:true},guitar:-1,camera:{position:camera.position.toArray(),target:target.toArray(),fov:camera.fov,aspect:camera.aspect},modelRevision:'v4-kitten-links-permanently-closed-eyes',simulationTime:stepClock}));
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
const picker=new THREE.Raycaster();canvas.addEventListener('click',e=>{picker.setFromCamera(new THREE.Vector2(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2),camera);selected=picker.intersectObject(cat.root,true).find(h=>h.object.visible&&!h.object.name.endsWith('Solid'))?.object.name||'';refresh()});
function dispose(){if(disposed)return;disposed=true;playing=false;renderer.setAnimationLoop(null);try{renderer.dispose()}catch{}scene.traverse(o=>{o.geometry?.dispose();if(o.isMesh){const mm=Array.isArray(o.material)?o.material:[o.material];for(const m of mm){m.map?.dispose();m.dispose()}}})}
addEventListener('pagehide',dispose);if(import.meta.hot)import.meta.hot.dispose(dispose);
try{await Promise.race([renderer.init(),new Promise((_,reject)=>setTimeout(()=>reject(Error('Isolated GPU initialization exceeded 30 seconds; no rendered frame verified.')),30000))]);if(!disposed){staticPose('rest');renderer.setAnimationLoop(now=>{if(disposed)return;const dt=Math.min(.05,(now-last)/1000);last=now;if(playing){advance(dt);target.copy(cat.root.getWorldPosition(new THREE.Vector3())).add(new THREE.Vector3(0,.34,0));setView(view)}renderer.render(scene,camera);frame++;recorder.tick();if(frame%15===0)refresh()});window.__IMG2THREEJS_READY__=true;refresh()}}catch(e){error.textContent=String(e.stack||e);refresh()}
