import {test} from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three/webgpu';import {CollisionWorld} from '../src/collision.js';
function room(){const r=new THREE.Group(),b=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshStandardNodeMaterial());b.position.set(1,1,0);r.add(b);r.scale.setScalar(.75);return r;}
test('oriented collision maintains local bounds under room scaling',()=>{const world=new CollisionWorld(room()),c=world.colliders[0];assert.equal(c.min.x,-.5);assert.equal(c.max.x,.5);assert.equal(c.bounds.min.x,.375);assert.equal(c.bounds.max.x,1.125);const p=world.resolve(.75,.75,0,.01);assert.ok(p[0]<.375||p[0]>1.125||p[1]<.375||p[1]>1.125||Math.abs(p[2])>.375);});
test('swept cloth cannot tunnel through a thin frame between simulation steps',()=>{const r=new THREE.Group(),m=new THREE.Mesh(new THREE.BoxGeometry(.008,1,1),new THREE.MeshStandardNodeMaterial());r.add(m);const w=new CollisionWorld(r);const p=w.resolve(.02,0,0,.005,[-.02,0,0]);assert.ok(p[0]<0);});
test('capsule displacement is blocked by furniture',()=>{const w=new CollisionWorld(room()),p=new THREE.Vector3(.1,1.63,0),q=w.movePlayer(p,.4,0);assert.ok(q.x<.5);});
test('animated animal solids keep current world bounds and breathing scale',()=>{const root=new THREE.Group(),cat=new THREE.Group();cat.userData.dynamicSolid=true;root.add(cat);const body=new THREE.Mesh(new THREE.SphereGeometry(.1),new THREE.MeshStandardNodeMaterial());cat.add(body);const w=new CollisionWorld(root);assert.equal(w.dynamic.length,1);cat.position.x=2;body.scale.y=1.1;w.update();assert.ok(w.colliders[0].bounds.min.x>1.89);assert.ok(Math.abs(w.colliders[0].scales[1]-1.1)<1e-6);});
test('cat floor navigation distinguishes walkable flooring from furniture and its own rig',()=>{const r=room(),floor=new THREE.Mesh(new THREE.BoxGeometry(6,.04,5),new THREE.MeshStandardNodeMaterial());floor.position.y=-.005;r.add(floor);const cat=new THREE.Group();cat.userData.dynamicSolid=true;r.add(cat);const body=new THREE.Mesh(new THREE.SphereGeometry(.15),new THREE.MeshStandardNodeMaterial());body.position.set(-1,.18,0);cat.add(body);const w=new CollisionWorld(r);assert.ok(w.floorFree(-.75,0,.25,.4,cat));assert.ok(!w.floorFree(.7,0,.25,.8,cat));assert.ok(w.supportHeight(-.75,0)<.04);});
test('cloth snapshots keep a roaming dynamic actor current outside the window region',()=>{const r=new THREE.Group(),cat=new THREE.Group();cat.userData.dynamicSolid=true;r.add(cat);cat.add(new THREE.Mesh(new THREE.SphereGeometry(.1),new THREE.MeshStandardNodeMaterial()));const w=new CollisionWorld(r);cat.position.set(2,.2,1);w.update();const dynamic=w.serializeClothSolids(true);assert.equal(dynamic.length,1);assert.ok(dynamic[0].bounds.min[0]>1.89);});
test('submillimeter plank seams neither block navigation nor drop paw support',()=>{const root=new THREE.Group(),material=new THREE.MeshStandardNodeMaterial();for(const x of[-.2503,.2503]){const plank=new THREE.Mesh(new THREE.BoxGeometry(.5,.03,2),material);plank.position.set(x,0,0);plank.userData.walkableSurface=true;root.add(plank);}const w=new CollisionWorld(root);for(let x=-.005;x<.005;x+=.0001){assert.ok(w.floorFree(x,0,.32,.48));assert.ok(w.supportHeight(x,0)>.014);} });
