import {test} from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three/webgpu';
import {indexExact,splitExact} from '../src/perf-geometry.js';import {imageDifference,compareBlocks} from '../src/perf-metrics.js';
import {scenePerformance} from '../src/perf-scene.js';import {setPerformanceOptions} from '../src/runtime-performance.js';import {CollisionWorld} from '../src/collision.js';
function triangles(g){const names=Object.keys(g.attributes).sort(),ids=g.index?.array??Array.from({length:g.attributes.position.count},(_,i)=>i),out=[];for(let i=0;i<ids.length;i+=3)out.push([...ids.slice(i,i+3)].map(j=>names.map(n=>{const a=g.attributes[n];return [...a.array.slice(j*a.itemSize,(j+1)*a.itemSize)];})));return out;}
test('exact indexing preserves every position, normal and UV in the original triangle order',()=>{const g=new THREE.BoxGeometry(2,2,2,3,3,3).toNonIndexed(),out=indexExact(g);assert.deepEqual(triangles(out),triangles(g));assert.ok(out.attributes.position.count<g.attributes.position.count);});
test('spatial chunks preserve the exact triangle multiset without cutting or duplicating faces',()=>{const g=new THREE.BoxGeometry(40,2,35,8,2,8).toNonIndexed(),parts=splitExact(g);assert.ok(parts.length>1);const key=x=>JSON.stringify(x),before=triangles(g).map(key).sort(),after=parts.flatMap(triangles).map(key).sort();assert.deepEqual(after,before);});
test('disabled spatial candidates are detached, so rejected trials leave no scene-traversal overhead',()=>{const root=new THREE.Group(),mesh=new THREE.Mesh(new THREE.BoxGeometry(40,2,35,8,2,8).toNonIndexed(),new THREE.MeshBasicMaterial());mesh.userData.staticBatch=true;root.add(mesh);const manager=scenePerformance({root},{dynamicSnapshots:null});setPerformanceOptions(['spatial_batches']);assert.ok(root.children.length>1);assert.equal(mesh.visible,false);setPerformanceOptions([]);assert.equal(root.children.length,1);assert.equal(mesh.visible,true);setPerformanceOptions(['spatial_batches']);assert.ok(root.children.length>1);setPerformanceOptions([]);manager.dispose();});
test('cached transforms remain live below an animated ancestor; static objects and key geometry stay correct',()=>{const root=new THREE.Group(),fixed=new THREE.Mesh(new THREE.BoxGeometry(),new THREE.MeshBasicMaterial()),moving=new THREE.Group(),child=new THREE.Mesh(new THREE.BoxGeometry(),new THREE.MeshBasicMaterial());moving.userData.dynamicSolid=true;moving.add(child);root.add(fixed,moving);const collision=new CollisionWorld(root),manager=scenePerformance({root},collision);setPerformanceOptions(['static_local','static_world']);assert.equal(fixed.matrixAutoUpdate,false);assert.equal(fixed.matrixWorldAutoUpdate,false);assert.equal(moving.matrixAutoUpdate,true);assert.equal(child.matrixWorldAutoUpdate,true);moving.position.x=2;root.updateMatrixWorld(true);assert.equal(child.matrixWorld.elements[12],2);setPerformanceOptions([]);assert.equal(fixed.matrixAutoUpdate,true);manager.dispose();});
test('dirty collider refresh detects exact moved bounds; snapshot reuse invalidates on movement',()=>{const root=new THREE.Group(),o=new THREE.Mesh(new THREE.BoxGeometry(),new THREE.MeshBasicMaterial());o.userData.dynamicSolid=true;root.add(o);const c=new CollisionWorld(root);setPerformanceOptions(['collision_dirty','collider_serialization']);c.update();const a=c.serializeClothSolids(true);c.update();assert.equal(c.serializeClothSolids(true),a);o.position.x=1;c.update();const b=c.serializeClothSolids(true);assert.notEqual(a,b);assert.equal(b[0].matrix[12],1);setPerformanceOptions([]);});
test('image gate is bit-identical for equal frames and rejects lost visual detail',()=>{const a=new Uint8ClampedArray(400).fill(128),b=a.slice();assert.equal(imageDifference(a,b).normalized_mae,0);assert.equal(imageDifference(a,b).pass,true);b.fill(0,0,40);assert.equal(imageDifference(a,b).pass,false);});
test('paired overall frame time weights views equally, separately from submission and GPU work',()=>{const blocks=[];for(const view of['room','keys'])for(const variant of['A','B','B','A'])blocks.push({view,variant,frames:Array.from({length:8},()=>({frame_ms:variant==='A'?20:16,cpu_ms:3,simulation_ms:1,submission_ms:2,gpu_ms:null,draw_calls:100,triangles:2000}))});const out=compareBlocks(blocks);assert.ok(Math.abs(out.aggregate.improvement_pct-20)<1e-8);assert.equal(out.aggregate.gpu_improvement_pct,null);assert.equal(out.aggregate.A.gpu_ms,null);assert.deepEqual(out.aggregate.improvement_ci95,[19.999999999999996,19.999999999999996]);});
