import {parseUsage,aggregateUsage} from '../src/usage-ledger.js';
import {developmentIntervals,aggregateDevelopmentTime} from '../src/development-time.js';
import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
const sessionId=process.env.CODEX_THREAD_ID||process.env.CODEX_SESSION_ID||'01a0f634-e041-79c1-bded-7f8404205548';
const sessionRoot=path.join(process.env.CODEX_HOME||path.join(process.env.HOME,'.codex'),'sessions');
function files(dir){if(!fs.existsSync(dir))return[];return fs.readdirSync(dir,{withFileTypes:true}).flatMap(d=>{const p=path.join(dir,d.name);return d.isDirectory()?files(p):d.name.endsWith('.jsonl')?[p]:[];});}
function read(file){return fs.readFileSync(file,'utf8').split('\n').filter(Boolean).flatMap(x=>{try{return[JSON.parse(x)]}catch{return[]}});}
const today=files(path.join(sessionRoot,'2026','10','01'));const file=today.find(p=>p.endsWith('-'+sessionId+'.jsonl'))||files(sessionRoot).find(p=>p.endsWith('-'+sessionId+'.jsonl'));
if(!file)throw Error('Current session usage log not found; no estimated token counts will be invented.');
const rootRows=read(file),main=parseUsage(rootRows,{id:sessionId,name:'Main studio agent',kind:'primary'}),ids=new Set([sessionId]),candidates=[],asOf=new Date().toISOString(),timeSources=[developmentIntervals(rootRows,sessionId,asOf)];
// Read only the small metadata header to discover descendants, never unrelated conversation content.
for(const f of today){if(f===file)continue;let meta;const fd=fs.openSync(f,'r');try{const b=Buffer.alloc(16384),n=fs.readSync(fd,b,0,b.length,0);meta=JSON.parse(b.subarray(0,n).toString().split('\n')[0]).payload;}catch{}finally{fs.closeSync(fd);}
 if(meta?.thread_source==='subagent'&&meta.source?.subagent?.thread_spawn)candidates.push({file:f,meta});}
const sources=[main];let changed=true;while(changed){changed=false;for(const c of candidates){if(ids.has(c.meta.id)||!ids.has(c.meta.parent_thread_id))continue;ids.add(c.meta.id);changed=true;const rows=read(c.file);timeSources.push(developmentIntervals(rows,c.meta.id,asOf));sources.push(parseUsage(rows,{id:c.meta.id,name:c.meta.agent_path?.split('/').at(-1)||c.meta.agent_nickname||'Delegated agent',kind:'subagent',parent_id:c.meta.parent_thread_id}));}}
const development_time=aggregateDevelopmentTime(timeSources,rootRows.find(r=>r.type==='session_meta')?.payload.timestamp||rootRows.find(r=>r.type==='session_meta')?.timestamp||'2026-10-01T06:44:15.000Z',asOf);
const report={session_id:sessionId,recorded_at:asOf,development_time,model:main.model,reasoning_effort:main.reasoning_effort,service_tier:main.service_tier??'not recorded (user requested Standard / no Fast)',...aggregateUsage(sources),pricing_source:'https://developers.openai.com/api/docs/pricing',pricing_verified_on:'2026-10-02',is_invoice:false,unpriced_tools:['ImageGen multi-view reference: provider billing not exposed by this session token log'],notes:['Measured primary + explicitly delegated descendant-agent counters; each source charged once.','Cumulative input includes context re-sends; not unique prompt length.','Cached input is a separately billed subset of input, never free.','Reasoning is included in output, not charged twice.','Only completed-step snapshots; in-flight output is not recorded yet.','Image generation charges and hidden policy-review/other provider costs are not inferred.']};
fs.mkdirSync(path.join(root,'progress'),{recursive:true});fs.writeFileSync(path.join(root,'progress/usage.json'),JSON.stringify(report,null,2)+'\n');
const t=report.tokens;fs.writeFileSync(path.join(root,'progress/COST.md'),`# Usage and API-equivalent cost\n\nModel: ${main.model||'not recorded'} · reasoning: ${main.reasoning_effort||'not recorded'} · requested speed: Standard / no Fast\n\nUsage as of ${report.usage_as_of} (UTC). Snapshot created ${report.recorded_at}.\n\nActive build time: ${(development_time.active_seconds/3600).toFixed(2)} hours · total elapsed: ${(development_time.elapsed_seconds/3600).toFixed(2)} hours · excluded idle: ${(development_time.idle_seconds/3600).toFixed(2)} hours.\n\n${development_time.method} This is logged active-task time, not a claim of continuous code editing.\n\n| Counter | Measured tokens |\n|---|---:|\n| Input (total) | ${t.input_tokens} |\n| Cached input (subset) | ${t.cached_input_tokens} |\n| Cache write (subset) | ${t.cache_write_input_tokens} |\n| Output (includes reasoning) | ${t.output_tokens} |\n| Reasoning (subset of output) | ${t.reasoning_output_tokens} |\n\n**API-equivalent estimate: $${report.api_equivalent_usd.toFixed(4)} USD. Not an invoice.**\n\nIncludes ${report.sources.length} measured sources:\n\n| Source | Model | Input | Cached input | Output | USD equivalent |\n|---|---|---:|---:|---:|---:|\n${report.sources.map(s=>`| ${s.name} | ${s.model||'not recorded'} | ${s.tokens.input_tokens} | ${s.tokens.cached_input_tokens} | ${s.tokens.output_tokens} | $${s.api_equivalent_usd.toFixed(4)} |`).join('\n')}\n\nRates verified October 2, 2026 from [official pricing](${report.pricing_source}). Cache-aware rates applied per completed prompt, including the long-context threshold if reached. Subagent counters are independent and deduplicated by source ID. Full steps in usage.json. In-flight responses are not yet recorded.\n\n**ImageGen reference-sheet charges are not exposed by these logs and are excluded, not assumed free.** Hidden policy-review/provider charges are also not inferred.\n\nRefresh with \`npm run usage\` inside this chat’s environment.\n`);
console.log(JSON.stringify({model:main.model,effort:main.reasoning_effort,sources:report.sources.map(s=>({name:s.name,tokens:s.tokens.total_tokens,cost:s.api_equivalent_usd})),tokens:report.tokens,api_equivalent_usd:report.api_equivalent_usd,as_of:report.usage_as_of}));
