import {guitarStringPCM,guitarBufferKey,fitGuitarNote} from './guitar-string.js';
import {guitarVoicing} from './composition.js';
import {composeAsync} from './music.js';
import {frequency,CHORDS} from './mechanics.js';
export const RECORDS=[
 {id:'blue',title:'Blue hour',subtitle:'Home sessions 001',bpm:86,key:'C major',root:60,duration:168,colors:['#273d50','#bc858c','#efc093'],description:'A soft piano, a borrowed sunset, and nowhere else to be.'},
 {id:'paper',title:'Paper moon',subtitle:'Bedroom demos 002',bpm:74,key:'A minor',root:57,duration:145,colors:['#525d57','#b5baa0','#e6d1a6'],description:'Quiet guitar sketches from the pages of a well-loved notebook.'},
 {id:'rain',title:'Tokyo rain',subtitle:'Window recordings 003',bpm:68,key:'D minor',root:62,duration:182,colors:['#4b526d','#9295b4','#d1b8aa'],description:'An electric piano melody for the last train home.'},
 {id:'little',title:'Little things',subtitle:'Sunday takes 004',bpm:96,key:'G major',root:55,duration:138,colors:['#c07455','#d7a875','#ebe2b6'],description:'The kind of morning that asks you to stay a little longer.'}
];
export class StudioAudio{
 constructor({workerFactory=null,generationTimeout=8000,fallbackGenerator=composeAsync}={}){Object.assign(this,{workerFactory,generationTimeout,fallbackGenerator});this.disposed=false;this.ctx=null;this.master=null;this.voices=new Map();this.sustained=new Set();this.sustain=false;this.volume=.65;this.muted=false;this.wave=null;this.record=RECORDS[0];this.recordBuffer=null;this.meter=0;this.take=[];this.recording=false;this.recordStart=0;this.node=null;this.initializing=null;this.buffers=new Map();this.messages=0;this.lastState=null;this.ready=false;this.pending=new Map();this.setupWorker();this.generate(this.record).catch(()=>{});}
 setupWorker(){if(this.worker)return true;this.workerJobs??=new Map();try{this.worker=this.workerFactory?this.workerFactory():new Worker(new URL('./music-worker.js',import.meta.url),{type:'module'});this.worker.onmessage=({data})=>{this.messages++;const job=this.workerJobs.get(data.id);if(data.error)job?.reject(Error(data.error));else job?.resolve(data);this.workerJobs.delete(data.id);};this.worker.onerror=e=>this.failWorker(e.message||'Record worker is unavailable in this browser.');this.worker.onmessageerror=()=>this.failWorker('Record worker response could not be read.');return true;}catch(e){this.workerError=e.message;return false;}}
 failWorker(message){this.workerError=message;for(const job of this.workerJobs.values())job.reject(Error(message));this.workerJobs.clear();this.worker?.terminate();this.worker=null;}
 async init(){if(this.initializing)return this.initializing;this.initializing=this._init();return this.initializing;}
 async _init(){this.ctx=new AudioContext({latencyHint:'interactive'});this.ctx.resume().catch(()=>{});this.setupWorker();this.master=this.ctx.createGain();this.master.gain.value=this.muted?0:this.volume;const comp=this.ctx.createDynamicsCompressor();comp.threshold.value=-14;comp.ratio.value=3;comp.attack.value=.003;comp.release.value=.18;this.recordDestination=this.ctx.createMediaStreamDestination();comp.connect(this.recordDestination);this.master.connect(comp);comp.connect(this.ctx.destination);this.analyser=this.ctx.createAnalyser();this.analyser.fftSize=256;this.meterData=new Float32Array(256);comp.connect(this.analyser);
  // Procedural small-room impulse, early reflections followed by frequency-damped decay.
  const convolver=this.ctx.createConvolver(),imp=this.ctx.createBuffer(2,this.ctx.sampleRate*1.3,this.ctx.sampleRate);let seed=9281;const random=()=>{seed=(seed*16807)%2147483647;return seed/2147483647*2-1;};for(let ch=0;ch<2;ch++){const d=imp.getChannelData(ch);for(let i=0;i<d.length;i++)d[i]=random()*Math.exp(-i/this.ctx.sampleRate*5.5)*.12;for(const [t,a] of[[.021,.42],[.038,.25],[.061,.18]])d[Math.floor((t+ch*.002)*this.ctx.sampleRate)]+=a;}convolver.buffer=imp;this.reverb=this.ctx.createGain();this.reverb.gain.value=.16;convolver.connect(this.reverb);this.reverb.connect(this.master);this.wet=convolver;
  this.ready=true;
  // Record loading is independent of playable instruments; a failed worker/worklet must not lock the whole studio.
  this.vinylInitializing=(async()=>{let timer;try{await Promise.race([this.ctx.audioWorklet.addModule(new URL('./vinyl-worklet.js',import.meta.url)),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('Record processor could not start. Reload the studio to retry.')),8000);})]);if(this.disposed)return;this.node=new AudioWorkletNode(this.ctx,'groove-reader',{outputChannelCount:[2]});this.node.port.onmessage=({data})=>{if(data.type==='clock'&&data.epoch===this.recordEpoch)this.recordClock=data;};this.node.onprocessorerror=()=>{this.vinylError='The record audio processor stopped. Reload to restart it.';};const hp=this.ctx.createBiquadFilter();hp.type='highpass';hp.frequency.value=22;const lp=this.ctx.createBiquadFilter();lp.type='lowpass';lp.frequency.value=15500;this.node.connect(hp);hp.connect(lp);lp.connect(this.master);lp.connect(this.wet);}finally{clearTimeout(timer);}})();
  this.vinylInitializing.then(()=>{if(!this.disposed)return this.loadRecord(this.record);}).catch(e=>{this.vinylError=e.message;});return true;}
 async resume(){const initializing=this.init();let resumeError;const request=this.ctx?.state==='running'?Promise.resolve():this.ctx.resume();request.catch(e=>{resumeError=e;});await initializing;if(this.ctx.state==='running')return;await new Promise((resolve,reject)=>{const deadline=Date.now()+6000;const check=()=>{if(this.ctx.state==='running')resolve();else if(resumeError)reject(resumeError);else if(Date.now()>=deadline||this.ctx.state==='closed')reject(Error('Sound is paused by the browser. Click Sound to try again.'));else setTimeout(check,40);};check();});}

 setVolume(v){this.volume=v;if(this.master)this.master.gain.setTargetAtTime(this.muted?0:v,this.ctx.currentTime,.02);}
 setMute(v){this.muted=v;this.setVolume(this.volume);}
 log(type,data){if(this.recording)this.take.push({t:this.ctx.currentTime-this.recordStart,type,...data});}
 pianoOn(midi,velocity=.7,timbre='piano',when=null,voiceKey=midi,duration=null){
  if(!this.ready)return;this.pianoOff(voiceKey,true);const c=this.ctx,t=Math.max(c.currentTime,when??c.currentTime),g=c.createGain();g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(velocity**1.6*.18,t+.005);g.gain.setTargetAtTime(velocity**1.6*.045,t+.025,1.9);g.connect(this.master);g.connect(this.wet);const f=frequency(midi),oscs=[];
  // Inharmonic modal bank. Each struck-string partial has an independent decay.
  for(let n=1;n<=8;n++){const o=c.createOscillator(),a=c.createGain();o.type='sine';o.frequency.value=f*n*Math.sqrt(1+.00007*n*n)*(timbre==='ep'?1:1);a.gain.setValueAtTime(Math.exp(-n*.2)/n**1.5*(timbre==='ep'&&n>3?.3:1),t);a.gain.setTargetAtTime(0,t+.015,Math.max(.15,3.5/n**.8)*(1.15-velocity*.25));o.connect(a);a.connect(g);o.start(t);o.stop(t+Math.max(12,(duration??0)+1));oscs.push(o);}
  // Hammer impact is a short deterministic broad-band transient.
  const b=c.createBuffer(1,Math.floor(c.sampleRate*.018),c.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.sin(i*1.314)*.6+Math.sin(i*.737)*.4)*Math.exp(-i/d.length*9);const s=c.createBufferSource(),a=c.createGain();s.buffer=b;a.gain.value=.045*velocity;s.connect(a);a.connect(g);s.start(t);
  const voice={g,oscs};if(duration!==null)g.gain.setTargetAtTime(0,t+Math.max(.01,duration),.11);this.voices.set(voiceKey,voice);oscs.at(-1).onended=()=>{if(this.voices.get(voiceKey)===voice)this.voices.delete(voiceKey);g.disconnect();};this.sustained.delete(midi);this.log('on',{midi,velocity});}
 pianoOff(midi,force=false){const v=this.voices.get(midi);if(!v)return;if(this.sustain&&!force){this.sustained.add(midi);return;}const t=this.ctx.currentTime;v.g.gain.cancelScheduledValues(t);v.g.gain.setTargetAtTime(0,t,.11);for(const o of v.oscs){try{o.stop(t+.7);}catch{}}this.voices.delete(midi);this.sustained.delete(midi);this.log('off',{midi});}
 setSustain(v){this.sustain=v;if(!v)for(const m of[...this.sustained])this.pianoOff(m,true);this.log('sustain',{value:v});}
 pluck(string,fret=0,velocity=.75,type=0,detune=0,when=null,duration=null,group='manual'){
  if(!this.ready)return;const c=this.ctx,buffer=this.guitarBuffer(string,fret,type,detune);
  const t=Math.max(c.currentTime,when??c.currentTime),src=c.createBufferSource(),g=c.createGain(),body=c.createBiquadFilter();src.buffer=buffer;g.gain.setValueAtTime((type===1?.24:.36)*velocity,t);body.type='peaking';body.frequency.value=type===2?230:145;body.Q.value=1.7;body.gain.value=4;src.connect(body);body.connect(g);g.connect(this.master);g.connect(this.wet);
  this.stringVoices??=new Map();const key=type+':'+string,previous=this.stringVoices.get(key);if(previous){previous.g.gain.setTargetAtTime(0,t,.015);try{previous.src.stop(t+.08);}catch{}}
  if(duration!==null)g.gain.setTargetAtTime(0,t+Math.max(.03,duration),.055);this.stringVoices.set(key,{src,g});this.guitarSources??=new Set();src.performanceGroup=group;this.guitarSources.add(src);src.onended=()=>{this.guitarSources.delete(src);if(this.stringVoices.get(key)?.src===src)this.stringVoices.delete(key);src.disconnect();g.disconnect();};src.start(t);this.log('pluck',{string,fret,velocity,type,detune});
 }

 guitarBuffer(string,fret,type=0,detune=0){this.guitarBuffers??=new Map();const key=guitarBufferKey(string,fret,type,detune);let buffer=this.guitarBuffers.get(key);if(!buffer){const data=guitarStringPCM(string,fret,type,detune,this.ctx.sampleRate);buffer=this.ctx.createBuffer(1,data.length,this.ctx.sampleRate);buffer.getChannelData(0).set(data);if(this.guitarBuffers.size>=64)this.guitarBuffers.delete(this.guitarBuffers.keys().next().value);this.guitarBuffers.set(key,buffer);}return buffer;}
 async prepareGuitarBuffers(events,guitars,{cancelled=()=>false,yieldTask=()=>new Promise(r=>setTimeout(r,0))}={}){const unique=new Map();for(const e of events){if(e.instrument==='keyboard')continue;const g=guitars[Number(e.instrument.split('-')[1])||0],f=fitGuitarNote(e.midi),voicing=e.chord?guitarVoicing(e.chord):tuningVoicing(f);for(let string=0;string<6;string++){const fret=voicing[string];if(fret<0||(e.string!==undefined&&e.string!==string))continue;const detune=g.detunes[string],key=guitarBufferKey(string,fret,g.type,detune);unique.set(key,[string,fret,g.type,detune]);}}let prepared=0;for(const args of unique.values()){if(cancelled())return false;this.guitarBuffer(...args);prepared++;await yieldTask();}this.preparedGuitarBuffers=prepared;return true;}

 strum(chord='C',type=0,detunes=[0,0,0,0,0,0],direction=1){const frets=CHORDS[chord]||CHORDS.C;const indices=direction>0?[0,1,2,3,4,5]:[5,4,3,2,1,0];indices.forEach((s,i)=>{if(frets[s]>=0)this.pluck(s,frets[s],.75-i*.025,type,detunes[s],this.ctx.currentTime+i*.024);});}
 async generate(record,side=0){const key=record.id+side;if(this.buffers.has(key))return this.buffers.get(key);if(this.pending.has(key))return this.pending.get(key);if(this.disposed)throw Error('The studio was closed.');const available=this.setupWorker();
  const workerResult=available?new Promise((resolve,reject)=>{const timer=setTimeout(()=>this.failWorker('Record worker timed out.'),this.generationTimeout);this.workerJobs.set(key,{resolve:b=>{clearTimeout(timer);resolve(b);},reject:e=>{clearTimeout(timer);reject(e);}});try{this.worker.postMessage({record,side,id:key});}catch(e){this.failWorker(e.message);}}):Promise.reject(Error(this.workerError||'Record worker unavailable.'));
  const promise=workerResult.then(b=>{this.generationBackend='worker';return b;}).catch(async e=>{if(this.disposed)throw e;this.workerError=e.message;this.generationBackend='cooperative-main';return this.fallbackGenerator(record,side,{cancelled:()=>this.disposed});}).then(b=>{if(this.disposed)throw Error('The studio was closed.');this.buffers.set(key,b);return b;}).finally(()=>this.pending.delete(key));this.pending.set(key,promise);return promise;}
 async loadRecord(record,side=0){this.record=record;this.recordSide=side;if(!this.ready)return;await this.vinylInitializing;if(!this.node)throw Error(this.vinylError||'Record processor unavailable.');const generation=(this.recordGeneration||0)+1;this.recordGeneration=generation;const b=await this.generate(record,side);if(generation!==this.recordGeneration)return;this.recordBuffer=b;this.loadedRecord=record.id+side;this.recordEpoch=(this.recordEpoch||0)+1;this.recordClock=null;this.node.port.postMessage({type:'buffer',data:b.data,sampleRate:b.sampleRate,epoch:this.recordEpoch});}
 async ensureRecord(){await this.resume();await this.vinylInitializing;if(this.vinylError)throw Error(this.vinylError);if(this.loadedRecord!==this.record.id+(this.recordSide||0))await this.loadRecord(this.record,this.recordSide||0);}
 async importFile(file){await this.resume();await this.vinylInitializing;if(file.size>50*1024*1024)throw Error('Choose audio smaller than 50 MB.');const decoded=await this.ctx.decodeAudioData(await file.arrayBuffer());if(decoded.duration>600)throw Error('Use a recording of 10 minutes or less.');const data=new Float32Array(decoded.length);for(let ch=0;ch<decoded.numberOfChannels;ch++){const d=decoded.getChannelData(ch);for(let i=0;i<d.length;i++)data[i]+=d[i]/decoded.numberOfChannels;}this.recordGeneration=(this.recordGeneration||0)+1;this.record={id:'custom'};this.recordSide=0;this.loadedRecord='custom0';this.recordBuffer={data,sampleRate:decoded.sampleRate};this.recordEpoch=(this.recordEpoch||0)+1;this.recordClock=null;this.node.port.postMessage({type:'buffer',data,sampleRate:decoded.sampleRate,epoch:this.recordEpoch});return decoded.duration;}
 applyRecordTransport(m){const clock=this.recordClock;if(!clock||m.scratching||m.ended||clock.revision!==m.transportRevision||clock.epoch!==this.recordEpoch)return;const prediction=clock.position+(clock.active?Math.max(0,this.ctx.currentTime-clock.time)*clock.rate:0);m.transport=Math.max(0,Math.min(m.duration,prediction));if(prediction>=m.duration){m.ended=true;m.stop();m.returnArm();}}
 sync(m){if(!this.node||this.vinylError)return;this.node.port.postMessage({type:'state',position:m.transport,revision:m.transportRevision,epoch:this.recordEpoch,scratching:m.scratching,rate:m.scratching?m.playbackRate:m.playbackRate*(1+m.wow+m.flutter),active:m.audible,noise:.0012+Math.abs(m.antiskate-m.trackingForce)*.0007});}
 beginTake(){if(!this.ready)return;this.take=[];this.recording=true;this.recordStart=this.ctx.currentTime;}
 endTake(){this.recording=false;return {format:'afterlight-performance-v1',created_at:new Date().toISOString(),concert_a:440,events:this.take};}
 getRMS(){if(!this.analyser)return 0;this.analyser.getFloatTimeDomainData(this.meterData);let energy=0;for(const v of this.meterData)energy+=v*v;return Math.sqrt(energy/this.meterData.length);}
 stopScore(group='score'){const prefix=group==='score'?'score:':'score:'+group+':';for(const key of[...this.voices.keys()])if(typeof key==='string'&&key.startsWith(prefix))this.pianoOff(key,true);for(const src of this.guitarSources||[]){if(src.performanceGroup!==group)continue;try{src.stop(this.ctx.currentTime+.06);}catch{}}}
 dispose(){this.disposed=true;this.failWorker('The studio was closed.');this.panic();this.ctx?.close();}
 panic(){for(const midi of[...this.voices.keys()])this.pianoOff(midi,true);this.sustain=false;this.sustained.clear();}
}

function tuningVoicing(note){const out=[-1,-1,-1,-1,-1,-1];if(note)out[note.string]=note.fret;return out;}
