import {cameraPlayMarkup,cameraSourceNotice,CAMERA_SOURCES} from './camera-play-view.js';
import {GestureMusic} from './gesture-music.js';
import {createPhoneReceiver,phoneOriginReady} from './phone-peer.js';
import {chordName,chordAt,progression,snapToKey,PROGRESSIONS} from './composition.js';
import {fitGuitarNote} from './composition-player.js';
export function mountCameraPlay({canvas,audio,keyboard,guitars,composer,ui,toast,onStart}){
  let worker,stream,receiver,busy=false,lastFrame=0,lastResult=0,active=false,token=0,raf=0,mode='magic',output='guitar-0',recording,recordStream,recordTimer,chunks=[],drawAt=0,source='computer',padChord=0,starting=false;
  const gesture=new GestureMusic(),held=new Map(),panel=document.createElement('section');panel.id='camera-play';panel.hidden=true;
  panel.innerHTML=cameraPlayMarkup();panel.setAttribute('aria-label','Hands play');
  document.querySelector('#app').append(panel);
  const pip=document.createElement('div');pip.id='performer-pip';pip.hidden=true;pip.innerHTML='<video autoplay playsinline muted></video><canvas width="320" height="180"></canvas><span id="performer-caption">Camera off</span>';document.querySelector('#app').append(pip);
  const video=pip.querySelector('video'),overlay=pip.querySelector('canvas'),paint=overlay.getContext('2d'),$=id=>panel.querySelector('#'+id);
  const button=document.createElement('button');button.id='camera-button';button.textContent='✋';button.setAttribute('aria-label','Open hands play');document.querySelector('.top-tools').append(button);button.onclick=()=>{panel.hidden=!panel.hidden;if(!panel.hidden){composer.hide();document.querySelector('#panel').hidden=true;refreshPalette();}};
  $('camera-close').onclick=()=>panel.hidden=true;
  function status(message){if($('camera-status').textContent!==message)$('camera-status').textContent=message;pip.querySelector('span').textContent=message;syncState();}
  function syncState(){$('camera-stop').disabled=!(active||receiver||starting);$('camera-local').disabled=starting||active;$('camera-local').textContent=starting?'Starting camera…':active&&source==='computer'?'Camera connected':'Enable computer camera';$('camera-record').disabled=!active&&recording?.state!=='recording';$('hands-dot').classList.toggle('on',active);button.classList.toggle('camera-live',active);}
  const securePhone=phoneOriginReady(location.origin);
  function chooseSource(next){stop();source=next;if(source==='pad')mode='magic';panel.querySelectorAll('[data-source]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.source===source)));for(const name of CAMERA_SOURCES)$('hands-'+name).hidden=name!==source;$('camera-mode').hidden=source==='pad';$('hands-mode-title').hidden=source==='pad';$('hands-instrument-step').textContent=source==='pad'?'02':'03';$('camera-phone').disabled=!securePhone;$('phone-setup').hidden=securePhone;refreshMode();status(source==='pad'?'Ready · no camera needed':'Camera off');}
  function refreshMode(){panel.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));$('hands-guide').textContent=source==='pad'?'Tap a chord below to try it.':mode==='magic'?'Raise or lower your hand to choose a chord. Sweep sideways to strum. Pinch to mute.':'Dip fingertips below the on-screen guide to play. Lift them to release.';$('camera-palette-label').hidden=mode!=='magic';$('camera-chords').hidden=mode!=='magic';}
  function refreshPalette(){$('camera-palette').innerHTML=PROGRESSIONS.map(p=>'<option value="'+p.id+'">'+p.name+'</option>').join('');$('camera-palette').value=composer.project.progression;$('camera-chords').innerHTML=progression(composer.project).chords.map((_,i)=>'<button data-hand-chord="'+i+'" aria-label="Play '+chordName(chordAt(composer.project,i))+' chord">'+chordName(chordAt(composer.project,i))+'</button>').join('');panel.querySelectorAll('[data-hand-chord]').forEach(b=>b.onclick=()=>{padChord=Number(b.dataset.handChord);focusOutput();strike(padChord,1,.65);});highlightChord(padChord);}
  function highlightChord(index){padChord=index;$('magic-chord').textContent=chordName(chordAt(composer.project,index));panel.querySelectorAll('[data-hand-chord]').forEach(b=>b.classList.toggle('active',Number(b.dataset.handChord)===index));}
  panel.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>chooseSource(b.dataset.source));panel.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{releaseHands();mode=b.dataset.mode;refreshMode();});
  $('camera-palette').onchange=e=>{releaseHands();composer.setProgression(e.target.value);padChord=0;refreshPalette();};
  for(const name of CAMERA_SOURCES)$(name==='computer'?'computer-notice':name==='phone'?'phone-notice':'pad-notice').textContent=cameraSourceNotice(name,securePhone);
  function releaseHands(){for(const [id,midi]of held){audio.pianoOff('camera:'+id,true);keyboard.release(midi,'camera:'+id);}held.clear();gesture.reset();}
  function stop(){token++;active=false;starting=false;cancelAnimationFrame(raf);worker?.terminate();worker=null;busy=false;stream?.getTracks().forEach(t=>t.stop());stream=null;receiver?.close();receiver=null;video.srcObject=null;pip.hidden=true;$('phone-link').hidden=true;$('phone-url').value='';$('phone-qr').getContext('2d').clearRect(0,0,192,192);releaseHands();if(recording?.state==='recording')recording.stop();status('Camera off');}
  async function tracking(nextStream,generation){
    if(generation!==token){nextStream.getTracks().forEach(t=>t.stop());return;}
    stream=nextStream;video.srcObject=stream;await video.play();if(generation!==token)return;pip.hidden=!$('camera-show').checked;status('Preparing hand tracking…');
    worker=new Worker(import.meta.env.BASE_URL+'hands/hand-worker.js');
    await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Hand detector initialization timed out.')),25000);worker.onmessage=({data})=>{if(data.type==='ready'){clearTimeout(timer);resolve();}else if(data.type==='error'){clearTimeout(timer);reject(Error(data.message));}};worker.onerror=e=>{clearTimeout(timer);reject(Error(e.message));};worker.postMessage({type:'init',wasm:new URL(import.meta.env.BASE_URL+'hands/wasm',location.origin).href,model:new URL(import.meta.env.BASE_URL+'hands/hand_landmarker.task',location.origin).href});});
    if(generation!==token)return;active=true;
    worker.onmessage=({data})=>{busy=false;if(data.type==='error'){stop();status('Tracking error: '+data.message);return;}if(data.type!=='landmarks')return;lastResult=performance.now();const hands=[...data.landmarks].sort((a,b)=>b[0].x-a[0].x);drawHands(hands);interpret(hands,data.time);};
    starting=false;status('Ready · show your hands');
    async function tick(now){if(!active||generation!==token)return;raf=requestAnimationFrame(tick);if(now-lastResult>500&&held.size)releaseHands();if(busy||now-lastFrame<83||video.readyState<2)return;busy=true;lastFrame=now;
      try{const bitmap=await createImageBitmap(video);if(generation!==token){bitmap.close();return;}worker.postMessage({type:'frame',bitmap,time:now},[bitmap]);}catch{busy=false;}}
    raf=requestAnimationFrame(tick);
  }
  function focusOutput(){onStart();if(output==='keyboard'||output==='band')ui.inspect('keyboard');else ui.inspect('guitars',Number(output.split('-')[1]));document.querySelector('#panel').hidden=true;}
  $('camera-local').onclick=async()=>{stop();starting=true;status('Starting camera…');const generation=token;try{if(!isSecureContext||!navigator.mediaDevices?.getUserMedia)throw Error('Camera access requires HTTPS or localhost in a supported browser.');await audio.resume();focusOutput();const id=$('camera-device').value;const next=await navigator.mediaDevices.getUserMedia({audio:false,video:{width:{ideal:960},height:{ideal:540},frameRate:{ideal:24,max:30},...(id?{deviceId:{exact:id}}:{facingMode:'user'})}});await tracking(next,generation);const devices=await navigator.mediaDevices.enumerateDevices();$('camera-device').replaceChildren();for(const d of devices.filter(d=>d.kind==='videoinput')){const o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||'Camera';$('camera-device').append(o);}}catch(e){if(generation===token){stop();status(e.message);}}};
  $('camera-phone').onclick=async()=>{stop();const generation=token;try{if(!securePhone)return;await audio.resume();focusOutput();const nextReceiver=await createPhoneReceiver(next=>tracking(next,generation).catch(e=>{if(generation===token){stop();status(e.message);}}),status,reason=>{if(generation===token){stop();status(reason);}});if(generation!==token){nextReceiver.close();return;}receiver=nextReceiver;$('phone-link').hidden=false;$('phone-url').value=receiver.url;const {default:QR}=await import('qrcode');if(generation!==token)return;await QR.toCanvas($('phone-qr'),receiver.url,{width:192,margin:2,errorCorrectionLevel:'M',color:{dark:'#243833',light:'#fffaf0'}});$('phone-expiry').textContent='Private pairing · expires '+new Date(receiver.expires).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});status('Waiting for your phone…');}catch(e){if(generation===token){stop();status(e.message);}}};
  $('phone-copy').onclick=async()=>{try{await navigator.clipboard.writeText($('phone-url').value);toast('Private phone pairing link copied.');}catch{ $('phone-url').select();}};
  $('camera-stop').onclick=stop;$('camera-show').onchange=e=>pip.hidden=!e.target.checked||!active;
  $('camera-instrument').onchange=e=>{releaseHands();output=e.target.value;if(active)focusOutput();};
  function strike(index,direction,velocity){highlightChord(index);const settings={...composer.project,backing:output==='band'?'guitar-0':output};
    composer.player.previewChord(settings,index,direction,output==='band'?velocity*.72:velocity).catch(e=>status(e.message));if(output==='band')composer.player.previewChord({...settings,backing:'keyboard'},index,direction,velocity*.60).catch(()=>{});
  }
  function interpret(hands,time){const state=gesture.update(hands,time,{mode,chordCount:progression(composer.project).chords.length});highlightChord(state.chord);
    for(const e of state.events){if(e.type==='mute'){composer.player.mutePreview();}else if(e.type==='strum')strike(e.chord,e.direction,e.velocity);else if(e.type==='on'){
      const midi=composer.project.snap?snapToKey(e.midi,composer.project.key,!!progression(composer.project).minor):e.midi;
      if(output==='keyboard'||output==='band'){held.set(e.id,midi);audio.pianoOn(midi,e.velocity,'piano',null,'camera:'+e.id);keyboard.press(midi,e.velocity,'camera:'+e.id);}
      if(output!=='keyboard'){const g=guitars[output==='band'?0:Number(output.split('-')[1])],f=fitGuitarNote(midi);if(f){audio.pluck(f.string,f.fret,e.velocity,g.type,g.detunes[f.string],null,null,'camera');g.vibrate(f.string,f.fret,e.velocity);}}
    }else if(e.type==='off'){audio.pianoOff('camera:'+e.id);keyboard.release(held.get(e.id)||e.midi,'camera:'+e.id);held.delete(e.id);}}
    if(!state.tracking)status('No hands found · move them into the frame.');else status(mode==='magic'?(state.pinched?'Pinch held · strum muted':'Magic · '+chordName(chordAt(composer.project,state.chord))):'Direct · dip fingers below the guide.');
  }
  function drawHands(hands){paint.clearRect(0,0,320,180);const scale=Math.min(320/(video.videoWidth||320),180/(video.videoHeight||180)),w=(video.videoWidth||320)*scale,h=(video.videoHeight||180)*scale,left=(320-w)/2,top=(180-h)/2;paint.strokeStyle='#a6d9ea';paint.fillStyle='#f8d7bb';paint.lineWidth=1.5;
    if(mode==='direct'){paint.beginPath();paint.moveTo(left,top+h*.60);paint.lineTo(left+w,top+h*.60);paint.stroke();}else{paint.beginPath();paint.moveTo(left+w/2,top);paint.lineTo(left+w/2,top+h);paint.stroke();}
    for(const hand of hands)for(const p of hand){paint.beginPath();paint.arc(left+(1-p.x)*w,top+p.y*h,2.4,0,Math.PI*2);paint.fill();}
  }
  const pad=$('magic-pad');let pointer=null,lastPad=-1000;
  pad.onpointerdown=e=>{audio.resume().catch(e=>status(e.message));focusOutput();pad.setPointerCapture(e.pointerId);const b=pad.getBoundingClientRect();const x=(e.clientX-b.left)/b.width;pointer={x,time:performance.now(),side:x<.47?-1:x>.53?1:0};};
  pad.onpointermove=e=>{const b=pad.getBoundingClientRect(),x=(e.clientX-b.left)/b.width,y=(e.clientY-b.top)/b.height,index=Math.max(0,Math.min(progression(composer.project).chords.length-1,Math.floor((1-y)*progression(composer.project).chords.length)));highlightChord(index);if(!pointer)return;const now=performance.now(),speed=(x-pointer.x)/Math.max(.01,(now-pointer.time)/1000);const side=x<.47?-1:x>.53?1:pointer.side;if(pointer.side&&side!==pointer.side&&now-lastPad>220){strike(index,speed>0?1:-1,Math.min(.85,.4+Math.abs(speed)*.12));lastPad=now;}pointer={x,time:now,side};};pad.onpointerup=()=>pointer=null;pad.onpointercancel=()=>pointer=null;pad.onkeydown=e=>{if(['ArrowUp','ArrowDown','Space','ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();e.stopPropagation();if(e.code==='ArrowUp'||e.code==='ArrowDown'){padChord=(padChord+(e.code==='ArrowUp'?1:-1)+progression(composer.project).chords.length)%progression(composer.project).chords.length;highlightChord(padChord);}else{focusOutput();strike(padChord,e.code==='ArrowLeft'?-1:1,.65);}}};
  const composite=document.createElement('canvas'),context=composite.getContext('2d');
  $('camera-record').onclick=async()=>{try{if(recording?.state==='recording'){recording.stop();return;}if(!active)throw Error('Start a camera before recording a performance.');await audio.resume();composite.width=1280;composite.height=720;recordStream=composite.captureStream(30);audio.recordDestination.stream.getAudioTracks().forEach(t=>recordStream.addTrack(t.clone()));const mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/mp4'].find(m=>MediaRecorder.isTypeSupported(m));if(!mime)throw Error('This browser has no supported performance-recording codec.');const takeStream=recordStream,takeChunks=[];recording=new MediaRecorder(takeStream,{mimeType:mime});const take=recording;take.ondataavailable=e=>{if(e.data.size)takeChunks.push(e.data);};let takeTimer;take.onstop=()=>{clearTimeout(takeTimer);const a=document.createElement('a'),url=URL.createObjectURL(new Blob(takeChunks,{type:mime}));a.href=url;a.download='afterlight-performance.'+(mime.startsWith('video/mp4')?'mp4':'webm');a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);takeStream.getTracks().forEach(t=>t.stop());if(recording===take){recording=null;$('camera-record').textContent='● Record performance';syncState();}};recording.start(1000);takeTimer=setTimeout(()=>{if(take.state==='recording'){take.stop();toast('Saved at the 10-minute recording safety limit.');}},600000);recordTimer=takeTimer;$('camera-record').textContent='■ Stop & save performance';}catch(e){toast(e.message);}};
  function captureTick(){if(recording?.state!=='recording'||performance.now()-drawAt<33)return;drawAt=performance.now();context.fillStyle='#111819';context.fillRect(0,0,1280,720);const fit=Math.min(1280/canvas.width,720/canvas.height);context.drawImage(canvas,(1280-canvas.width*fit)/2,(720-canvas.height*fit)/2,canvas.width*fit,canvas.height*fit);if($('camera-show').checked&&video.readyState>=2){context.save();context.translate(1256,526);context.scale(-1,1);const fit=Math.min(288/video.videoWidth,162/video.videoHeight);context.fillStyle='#172323';context.fillRect(0,0,288,162);context.drawImage(video,(288-video.videoWidth*fit)/2,(162-video.videoHeight*fit)/2,video.videoWidth*fit,video.videoHeight*fit);context.restore();context.strokeStyle='#f6e4d0';context.lineWidth=3;context.strokeRect(968,526,288,162);}}
  addEventListener('keydown',e=>{if(e.code==='Escape'&&active)stop();});addEventListener('pagehide',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden&&active)stop();});
  refreshPalette();chooseSource('computer');
  return{show(){panel.hidden=false;},stop,captureTick,get state(){return{active,mode,output,recording:recording?.state==='recording',source:active?source:'off',selectedSource:source};}};
}
