import {RoomTour} from './room-tour.js';
import * as THREE from 'three/webgpu';import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
export function cameraRig(camera,canvas,room,collision){const orbit=new OrbitControls(camera,canvas);orbit.enabled=false;orbit.enableDamping=true;orbit.minDistance=.3;orbit.maxDistance=20;orbit.maxPolarAngle=Math.PI*.49;let mode='sofa',yaw=.14,pitch=.04,transition=null,drag=null;const move=new Set(),tour=new RoomTour(camera,collision);
 const views={tour:{p:[-1.67,1.26,1.91],t:[-1.0,1.42,-2.7],live:false},concert:{p:[-1.69,2.15,1.65],t:[-1.69,1.78,-2.09],live:false},sofa:{p:[-1.67,1.26,1.91],t:[-1.0,1.42,-2.7],live:true},walk:{p:[-.32,1.63,1.70],t:[-.0,1.6,-2.4],live:true},room:{p:[8.8,7.4,11.1],t:[-.25,1.15,-.5],live:false},turntable:{p:[2.05,2.01,2.1],t:[1.3,1.21,.66],live:false},keyboard:{p:[-1.69,2.15,-.90],t:[-1.69,1.22,-2.13],live:false},guitars:{p:[-.10,1.85,1.22],t:[-.30,1.75,-1.0],live:false},beanbag:{p:[2.9,1.03,2.33],t:[2.4,1.3,-2.8],live:true}};
 for(const v of Object.values(views)){v.p=v.p.map(x=>x*.75);v.t=v.t.map(x=>x*.75);}views.sofa.p=[-1.18,1.18,1.58];views.sofa.t=[-.35,1.08,-1.76];views.walk.p=[.03,1.63,1.28];views.walk.t[1]=1.56;views.beanbag.p[1]=1.05;views.turntable.p=[1.29,1.35,1.25];views.turntable.t=[1.027,.87,.495];
 function choose(name,instant=false){name=Object.hasOwn(views,name)?name:'sofa';if(import.meta.env.DEV)sessionStorage.setItem('afterlight-view',name);const v=views[name];tour.stop();mode=name;drag=null;move.clear();orbit.enabled=!v.live&&name!=='tour';orbit.enableZoom=name!=='guitars';const endFov=name==='room'?39:v.live?64:45;const startFov=camera.fov;if(instant){camera.fov=endFov;camera.updateProjectionMatrix();}for(const wall of room.enclosure||[])wall.visible=name!=='room';if(room.city)room.city.visible=name!=='room';if(room.cutawayBackdrop)room.cutawayBackdrop.visible=name==='room';document.body.classList.toggle('live-mode',v.live);document.body.classList.toggle('overview-mode',name==='room');document.body.classList.toggle('tour-mode',name==='tour');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.querySelector('#hint').innerHTML=v.live?'DRAG TO LOOK <b>·</b> WASD TO WALK <b>·</b> E TO INTERACT':'DRAG TO ORBIT <b>·</b> SCROLL TO ZOOM <b>·</b> C TO SIT BACK DOWN';
  if(name==='tour'){transition=null;tour.start();orbit.target.copy(tour.target);return;}
  const p=new THREE.Vector3(...v.p),t=new THREE.Vector3(...v.t);const d=t.clone().sub(p).normalize();yaw=Math.atan2(d.x,-d.z);pitch=Math.asin(d.y);if(instant){camera.position.copy(p);orbit.target.copy(t);camera.lookAt(t);}else transition={start:performance.now(),startFov,endFov,p:camera.position.clone(),q:camera.quaternion.clone(),end:p,t}; }
 const remembered=import.meta.env.DEV?sessionStorage.getItem('afterlight-view'):null;choose(remembered&&!['tour','concert'].includes(remembered)?remembered:'sofa',true);
 function direction(){return new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch));}
 canvas.addEventListener('pointerdown',e=>{if(views[mode]?.live&&e.button===0)drag={x:e.clientX,y:e.clientY};});
 window.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;yaw+=dx*.0025;pitch=Math.max(-1.1,Math.min(1.1,pitch-dy*.0022));drag={x:e.clientX,y:e.clientY};transition=null;});window.addEventListener('pointerup',()=>drag=null);
 canvas.addEventListener('wheel',e=>{if(mode==='guitars'){camera.fov=Math.max(30,Math.min(66,camera.fov+Math.sign(e.deltaY)*2));camera.updateProjectionMatrix();return;}if(!views[mode]?.live)return;camera.fov=Math.max(38,Math.min(78,camera.fov+Math.sign(e.deltaY)*2));camera.updateProjectionMatrix();if(camera.fov===78&&e.deltaY>0)choose('room');},{passive:true});
 window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(views[mode]?.live&&['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)){move.add(e.code);e.preventDefault();if(mode==='sofa'||mode==='beanbag')choose('walk');}});
 window.addEventListener('keyup',e=>move.delete(e.code));window.addEventListener('blur',()=>move.clear());
 const obstacles=[[-3.53,.12,-3.15,-1.72],[.39,3.02,.11,1.24],[1.60,4.13,-3.23,-2.47],[-3.03,-.37,1.48,2.6],[-2.37,-1.43,.25,.89],[2.26,3.94,1.57,3.0]];
 function free(x,z){if(x< -3.89||x>3.89||z< -3.03||z>3.03)return false;const r=.16;return !obstacles.some(([x0,x1,z0,z1])=>x>x0-r&&x<x1+r&&z>z0-r&&z<z1+r);}
 return{orbit,choose,tour,get mode(){return mode;},get live(){return !!views[mode]?.live;},update(dt){if(mode==='tour'){const done=tour.update(dt);orbit.target.copy(tour.target);if(done)choose('sofa',true);return;}if(transition){const t=Math.min(1,(performance.now()-transition.start)/900),k=t*t*(3-2*t);camera.position.lerpVectors(transition.p,transition.end,k);camera.fov=transition.startFov+(transition.endFov-transition.startFov)*k;camera.updateProjectionMatrix();const q=new THREE.Quaternion();const m=new THREE.Matrix4().lookAt(transition.end,transition.t,new THREE.Vector3(0,1,0));q.setFromRotationMatrix(m);camera.quaternion.slerpQuaternions(transition.q,q,k);orbit.target.copy(transition.t);if(t===1)transition=null;return;}
  if(views[mode]?.live){if(move.size){let forward=(move.has('KeyW')||move.has('ArrowUp')?1:0)-(move.has('KeyS')||move.has('ArrowDown')?1:0),right=(move.has('KeyD')||move.has('ArrowRight')?1:0)-(move.has('KeyA')||move.has('ArrowLeft')?1:0);const norm=Math.hypot(forward,right)||1;const step=dt*1.5;const dx=(Math.sin(yaw)*forward+Math.cos(yaw)*right)/norm*step,dz=(-Math.cos(yaw)*forward+Math.sin(yaw)*right)/norm*step;const q=collision.movePlayer(camera.position,dx,dz);camera.position.x=q.x;camera.position.z=q.z;camera.position.y=1.63;}camera.lookAt(camera.position.clone().add(direction()));}else{orbit.update();}}};
}
