import {CurtainCloth} from './cloth.js';
let cloths=[],solids=[],scale=.75,hash=new Map();const cell=.40;const key=(x,y,z)=>Math.floor(x/cell)+','+Math.floor(y/cell)+','+Math.floor(z/cell);
function index(){hash=new Map();for(const c of solids){const b=c.bounds;for(let x=Math.floor((b.min[0]-.012)/cell);x<=Math.floor((b.max[0]+.012)/cell);x++)for(let y=Math.floor((b.min[1]-.012)/cell);y<=Math.floor((b.max[1]+.012)/cell);y++)for(let z=Math.floor((b.min[2]-.012)/cell);z<=Math.floor((b.max[2]+.012)/cell);z++){const k=x+','+y+','+z,l=hash.get(k)||[];l.push(c);hash.set(k,l);}}}
function project(p,old,i){let px=p[i],py=p[i+1],pz=p[i+2],r=.006;for(const c of hash.get(key(px,py,pz))||[]){const b=c.bounds;if(Math.max(px,old[i])+r<b.min[0]||Math.min(px,old[i])-r>b.max[0]||Math.max(py,old[i+1])+r<b.min[1]||Math.min(py,old[i+1])-r>b.max[1]||Math.max(pz,old[i+2])+r<b.min[2]||Math.min(pz,old[i+2])-r>b.max[2])continue;const im=c.inverse,m=c.matrix;let lx=im[0]*px+im[4]*py+im[8]*pz+im[12],ly=im[1]*px+im[5]*py+im[9]*pz+im[13],lz=im[2]*px+im[6]*py+im[10]*pz+im[14];const [sx,sy,sz]=c.scales,lo=[c.min[0]-r/sx,c.min[1]-r/sy,c.min[2]-r/sz],hi=[c.max[0]+r/sx,c.max[1]+r/sy,c.max[2]+r/sz];let hit=false;
 if(c.type==='ellipsoid'){const rr=c.radius+r/Math.min(sx,sy,sz),d=Math.sqrt(lx*lx+ly*ly+lz*lz);if(d<rr){const q=rr/(d||.0001);lx*=q;ly*=q;lz*=q;hit=true;}}
 else if(lx>lo[0]&&lx<hi[0]&&ly>lo[1]&&ly<hi[1]&&lz>lo[2]&&lz<hi[2]){const v=[lx,ly,lz],s=[sx,sy,sz];let best=Infinity,axis=0,end=0;for(let a=0;a<3;a++){const dl=(v[a]-lo[a])*s[a],dh=(hi[a]-v[a])*s[a];if(dl<best){best=dl;axis=a;end=lo[a]-.0002/s[a];}if(dh<best){best=dh;axis=a;end=hi[a]+.0002/s[a];}}v[axis]=end;[lx,ly,lz]=v;hit=true;}
 else{const o=[im[0]*old[i]+im[4]*old[i+1]+im[8]*old[i+2]+im[12],im[1]*old[i]+im[5]*old[i+1]+im[9]*old[i+2]+im[13],im[2]*old[i]+im[6]*old[i+1]+im[10]*old[i+2]+im[14]],v=[lx,ly,lz];let enter=0,exit=1,valid=true;for(let a=0;a<3;a++){const d=v[a]-o[a];if(Math.abs(d)<1e-9){if(o[a]<lo[a]||o[a]>hi[a])valid=false;continue;}let t0=(lo[a]-o[a])/d,t1=(hi[a]-o[a])/d;if(t0>t1)[t0,t1]=[t1,t0];enter=Math.max(enter,t0);exit=Math.min(exit,t1);}if(valid&&enter>0&&enter<exit&&enter<1){const t=Math.max(0,enter-.0001);lx=o[0]+(lx-o[0])*t;ly=o[1]+(ly-o[1])*t;lz=o[2]+(lz-o[2])*t;hit=true;}}
 if(hit){px=m[0]*lx+m[4]*ly+m[8]*lz+m[12];py=m[1]*lx+m[5]*ly+m[9]*lz+m[13];pz=m[2]*lx+m[6]*ly+m[10]*lz+m[14];}}
 p[i]=px;p[i+1]=py;p[i+2]=pz;}
function send(){const positions=cloths.map(c=>c.p.slice());self.postMessage({type:'state',positions},positions.map(p=>p.buffer));}
self.onmessage=({data:m})=>{if(m.type==='init'){scale=m.scale;solids=m.solids;index();cloths=m.parameters.map(p=>{const c=new CurtainCloth(p);c.collide=project;return c;});send();}if(m.type==='step'){if(m.coverage)m.coverage.forEach((p,i)=>cloths[i].setCoverage(p.width,p.edge));if(m.dynamic){solids=[...solids.filter(c=>!c.dynamic),...m.dynamic];index();}const steps=Math.max(1,Math.min(4,Math.round(m.dt*60)));for(let i=0;i<steps;i++)for(const c of cloths){c.wind=m.wind;c.step(1/60);}send();}};
