/** Position-based cloth: SI lengths; pinned rail, structural/shear/bend constraints, gravity + aerodynamic drag. */
export class CurtainCloth{
 constructor({cols=12,rows=22,width=.55,height=2.64,edge=-2.66,x=-3.96,top=3.48,seed=0,pleat=.035,materialWidth=null}={}){this.materialWidth=materialWidth??width;this.coverage={width,edge,x,top,height};this.gathered=materialWidth!==null;this.cols=cols;this.rows=rows;this.count=cols*rows;this.p=new Float32Array(this.count*3);this.old=new Float32Array(this.count*3);this.rest=new Float32Array(this.count*3);this.constraints=[];this.t=seed;this.wind=1.25;this.wallX=x-.05;this.floor=.05;
  for(let y=0;y<rows;y++)for(let c=0;c<cols;c++){const i=y*cols+c,z=edge+c/(cols-1)*width,fold=this.gathered?(-1)**c*.5*Math.sqrt(Math.max(0,(this.materialWidth/(cols-1))**2-(width/(cols-1))**2)):Math.cos(c/(cols-1)*Math.PI*10)*pleat;this.p.set([x+fold,top-y/(rows-1)*height,z],i*3);}this.old.set(this.p);this.rest.set(this.p);
  const connect=(a,b,stiffness=1)=>{const ai=a*3,bi=b*3,r=Math.hypot(this.p[ai]-this.p[bi],this.p[ai+1]-this.p[bi+1],this.p[ai+2]-this.p[bi+2]);const ax=a%cols,bx=b%cols,ay=Math.floor(a/cols),by=Math.floor(b/cols),length=this.gathered?Math.hypot((bx-ax)*this.materialWidth/(cols-1),(by-ay)*height/(rows-1)):r;this.constraints.push({a,b,r:length,stiffness});};
  for(let y=0;y<rows;y++)for(let c=0;c<cols;c++){const i=y*cols+c;if(c+1<cols)connect(i,i+1);if(y+1<rows)connect(i,i+cols);if(c+1<cols&&y+1<rows){connect(i,i+cols+1,.72);connect(i+1,i+cols,.72);}if(y+2<rows)connect(i,i+cols*2,.20);if(c+2<cols)connect(i,i+2,this.gathered?.015:.12);}
 }
 setCoverage(width,edge){if(!this.gathered)return;const {x,top}=this.coverage;const amplitude=.5*Math.sqrt(Math.max(0,(this.materialWidth/(this.cols-1))**2-(width/(this.cols-1))**2));for(let c=0;c<this.cols;c++)this.rest.set([x+(-1)**c*amplitude,top,edge+c/(this.cols-1)*width],c*3);}
 step(dt){dt=Math.min(dt,.02);this.t+=dt;const p=this.p,old=this.old,dt2=dt*dt,airDensity=1.225,dragCoefficient=.9,surfaceDensity=.18;const gust=this.wind*(.78+.18*Math.sin(this.t*.91)+.13*Math.sin(this.t*1.7));
  for(let i=this.cols;i<this.count;i++){const j=i*3,y=Math.floor(i/this.cols)/(this.rows-1),z=p[j+2],vx=(p[j]-old[j])/dt,relative=gust-vx;const force=.5*airDensity*dragCoefficient/surfaceDensity*relative*Math.abs(relative);const sway=Math.sin(this.t*1.3+z*2.7)*.22*this.wind*y;const x=p[j],yy=p[j+1],zz=p[j+2];p[j]=x+(x-old[j])*.988+Math.max(-9,Math.min(9,force))*dt2;p[j+1]=yy+(yy-old[j+1])*.994-9.81*dt2;p[j+2]=zz+(zz-old[j+2])*.985+sway*dt2;old[j]=x;old[j+1]=yy;old[j+2]=zz;}
  for(let iter=0;iter<5;iter++){for(const q of this.constraints){const a=q.a*3,b=q.b*3,dx=p[b]-p[a],dy=p[b+1]-p[a+1],dz=p[b+2]-p[a+2],d=Math.sqrt(dx*dx+dy*dy+dz*dz)||1e-5,f=(d-q.r)/d*q.stiffness;const wa=q.a<this.cols?0:.5,wb=q.b<this.cols?0:.5,total=wa+wb||1;const ca=f*wa/total,cb=f*wb/total;p[a]+=dx*ca;p[a+1]+=dy*ca;p[a+2]+=dz*ca;p[b]-=dx*cb;p[b+1]-=dy*cb;p[b+2]-=dz*cb;}for(let i=this.cols;i<this.count;i++)if(this.collide&&iter===4)this.collide(p,old,i*3);for(let i=0;i<this.cols*3;i++)p[i]=this.rest[i];for(let i=this.cols;i<this.count;i++){const j=i*3;p[j]=Math.max(this.wallX,p[j]);p[j+1]=Math.max(this.floor,p[j+1]);}}
 }
}
