import {hasPerf} from './runtime-performance.js';
import * as THREE from 'three/webgpu';
/** Spatial-hashed oriented solid colliders for the authored room. Cloth uses swept point tests; player uses a capsule sampled by spheres. */
export class CollisionWorld{
 constructor(root){this.root=root;this.scale=root.scale.x;this.hash=new Map();this.dynamic=[];this.colliders=[];this.cell=.45;this.out=[0,0,0];root.updateWorldMatrix(true,true);root.traverse(o=>{let a=o;while(a&&a!==root){if(a.userData.nonPhysical)return;a=a.parent;}if(!o.isMesh||o.isInstancedMesh||o.userData.dynamic||o.geometry.type==='PlaneGeometry'||o.material?.side===THREE.BackSide)return;const box=o.geometry.boundingBox|| (o.geometry.computeBoundingBox(),o.geometry.boundingBox);if(!box)return;const size=new THREE.Vector3();box.getSize(size);if(Math.min(size.x,size.y,size.z)<.0004)return;let p=o,dynamic=false;while(p&&p!==root){if(p.userData.dynamic||p.userData.dynamicSolid||['window','arm','key','lid','cue','pitch','scratch'].includes(p.userData.action))dynamic=true;p=p.parent;}const c={object:o,min:box.min.clone(),max:box.max.clone(),matrix:o.matrixWorld.clone(),inverse:o.matrixWorld.clone().invert(),type:o.geometry.type==='SphereGeometry'?'ellipsoid':'box',radius:o.geometry.parameters?.radius||1,dynamic};c.scales=[Math.hypot(c.matrix.elements[0],c.matrix.elements[1],c.matrix.elements[2]),Math.hypot(c.matrix.elements[4],c.matrix.elements[5],c.matrix.elements[6]),Math.hypot(c.matrix.elements[8],c.matrix.elements[9],c.matrix.elements[10])];c.bounds=new THREE.Box3(c.min.clone(),c.max.clone()).applyMatrix4(c.matrix);this.colliders.push(c);if(dynamic)this.dynamic.push(c);else this.insert(c);});}
 key(x,y,z){return Math.floor(x/this.cell)+','+Math.floor(y/this.cell)+','+Math.floor(z/this.cell);}
 insert(c){const b=new THREE.Box3(c.min.clone(),c.max.clone()).applyMatrix4(c.matrix).expandByScalar(.025);const lo=b.min,hi=b.max;for(let x=Math.floor(lo.x/this.cell);x<=Math.floor(hi.x/this.cell);x++)for(let y=Math.floor(lo.y/this.cell);y<=Math.floor(hi.y/this.cell);y++)for(let z=Math.floor(lo.z/this.cell);z<=Math.floor(hi.z/this.cell);z++){const key=x+','+y+','+z,a=this.hash.get(key)||[];a.push(c);this.hash.set(key,a);}}
 update(){let changed=false;if(hasPerf('collision_dirty'))this.root.updateWorldMatrix(true,true);for(const c of this.dynamic){if(!hasPerf('collision_dirty'))c.object.updateWorldMatrix(true,false);else if(c.matrix.equals(c.object.matrixWorld))continue;changed=true;c.matrix.copy(c.object.matrixWorld);c.inverse.copy(c.matrix).invert();c.scales=[Math.hypot(c.matrix.elements[0],c.matrix.elements[1],c.matrix.elements[2]),Math.hypot(c.matrix.elements[4],c.matrix.elements[5],c.matrix.elements[6]),Math.hypot(c.matrix.elements[8],c.matrix.elements[9],c.matrix.elements[10])];c.bounds.set(c.min,c.max).applyMatrix4(c.matrix);}if(changed){this.dynamicRevision=(this.dynamicRevision||0)+1;this.dynamicSnapshots=null;}}
 candidates(x,y,z,r=0){if(!r)return [...(this.hash.get(this.key(x,y,z))||[]),...this.dynamic];const found=new Set(this.dynamic);for(let a=-1;a<=1;a++)for(let b=-1;b<=1;b++)for(let c=-1;c<=1;c++)for(const q of this.hash.get(this.key(x+a*r,y+b*r,z+c*r))||[])found.add(q);return [...found];}
 resolve(x,y,z,r=.008,old=null,horizontal=false){let px=x,py=y,pz=z;const candidates=r<.03?[...(this.hash.get(this.key(x,y,z))||[]),...this.dynamic]:this.candidates(x,y,z,r);for(const c of candidates){const bb=c.bounds;if(Math.max(px,old?.[0]??px)+r<bb.min.x||Math.min(px,old?.[0]??px)-r>bb.max.x||Math.max(py,old?.[1]??py)+r<bb.min.y||Math.min(py,old?.[1]??py)-r>bb.max.y||Math.max(pz,old?.[2]??pz)+r<bb.min.z||Math.min(pz,old?.[2]??pz)-r>bb.max.z)continue;const im=c.inverse.elements,m=c.matrix.elements;let lx=im[0]*px+im[4]*py+im[8]*pz+im[12],ly=im[1]*px+im[5]*py+im[9]*pz+im[13],lz=im[2]*px+im[6]*py+im[10]*pz+im[14];const [sx,sy,sz]=c.scales;const lo=[c.min.x-r/sx,c.min.y-r/sy,c.min.z-r/sz],hi=[c.max.x+r/sx,c.max.y+r/sy,c.max.z+r/sz];let hit=false;
  if(c.type==='ellipsoid'){const rr=c.radius+r/Math.min(sx,sy,sz),d=Math.hypot(lx,ly,lz);if(d<rr){const s=rr/(d||.001);lx*=s;ly*=s;lz*=s;hit=true;}}
  else if(lx>lo[0]&&lx<hi[0]&&ly>lo[1]&&ly<hi[1]&&lz>lo[2]&&lz<hi[2]){const v=[lx,ly,lz],sc=[sx,sy,sz];let axis=0,best=Infinity,end=0;for(let a=0;a<3;a++){if(horizontal&&a===1)continue;const dl=(v[a]-lo[a])*sc[a],dh=(hi[a]-v[a])*sc[a];if(dl<best){axis=a;best=dl;end=lo[a]-.0002/sc[a];}if(dh<best){axis=a;best=dh;end=hi[a]+.0002/sc[a];}}v[axis]=end;[lx,ly,lz]=v;hit=true;}
  else if(old){const ox=im[0]*old[0]+im[4]*old[1]+im[8]*old[2]+im[12],oy=im[1]*old[0]+im[5]*old[1]+im[9]*old[2]+im[13],oz=im[2]*old[0]+im[6]*old[1]+im[10]*old[2]+im[14],a=[ox,oy,oz],b=[lx,ly,lz];let enter=0,exit=1,valid=true;for(let k=0;k<3;k++){const d=b[k]-a[k];if(Math.abs(d)<1e-9){if(a[k]<lo[k]||a[k]>hi[k])valid=false;continue;}let t0=(lo[k]-a[k])/d,t1=(hi[k]-a[k])/d;if(t0>t1)[t0,t1]=[t1,t0];enter=Math.max(enter,t0);exit=Math.min(exit,t1);}if(valid&&enter>0&&enter<exit&&enter<1){const t=Math.max(0,enter-.0002);lx=ox+(lx-ox)*t;ly=oy+(ly-oy)*t;lz=oz+(lz-oz)*t;hit=true;}}
  if(hit){px=m[0]*lx+m[4]*ly+m[8]*lz+m[12];py=m[1]*lx+m[5]*ly+m[9]*lz+m[13];pz=m[2]*lx+m[6]*ly+m[10]*lz+m[14];}
 }this.out[0]=px;this.out[1]=py;this.out[2]=pz;return this.out;}
 resolveCloth(p,old,i){const s=this.scale,q=this.resolve(p[i]*s,p[i+1]*s,p[i+2]*s,.005,[old[i]*s,old[i+1]*s,old[i+2]*s]);p[i]=q[0]/s;p[i+1]=q[1]/s;p[i+2]=q[2]/s;}
 serializeClothSolids(dynamicOnly=false){if(dynamicOnly&&hasPerf('collider_serialization')&&this.dynamicSnapshots)return this.dynamicSnapshots;const snapshots=this.colliders.flatMap((c,id)=>{const b=c.bounds;if(dynamicOnly?!c.dynamic:!c.dynamic&&(b.max.x< -3.3||b.min.x> -1.65||b.max.z< -2.3||b.min.z>1.2))return[];return[{id,dynamic:c.dynamic,type:c.type,radius:c.radius,min:c.min.toArray(),max:c.max.toArray(),matrix:[...c.matrix.elements],inverse:[...c.inverse.elements],scales:c.scales,bounds:{min:b.min.toArray(),max:b.max.toArray()}}];});if(dynamicOnly&&hasPerf('collider_serialization'))this.dynamicSnapshots=snapshots;return snapshots;}
 isUnder(object,ancestor){if(!ancestor)return false;let o=object;while(o){if(o===ancestor)return true;o=o.parent;}return false;}
 supportHeight(x,z,maxY=.11,ignore=null){let top=0;const pad=.010;for(const c of this.candidates(x,.04,z,.08)){if(this.isUnder(c.object,ignore))continue;const b=c.bounds;if(b.max.y>maxY||b.max.y<top||x+pad<b.min.x||x-pad>b.max.x||z+pad<b.min.z||z-pad>b.max.z)continue;top=b.max.y;}return top;}
 floorFree(x,z,r=.29,height=.40,ignore=null){
  if(x-r< -3.07||x+r>3.07||z-r< -2.4||z+r>2.4)return false;
  const floor=this.supportHeight(x,z,.11,ignore),found=new Set();for(const y of[floor+.08,floor+.23,floor+height])for(const c of this.candidates(x,y,z,r))found.add(c);
  for(const c of found){if(this.isUnder(c.object,ignore))continue;const b=c.bounds;if(c.object.userData.walkableSurface||b.max.y<.04||b.max.y<floor+.016||b.min.y>floor+height)continue;const dx=Math.max(b.min.x-x,0,x-b.max.x),dz=Math.max(b.min.z-z,0,z-b.max.z);if(dx*dx+dz*dz<r*r)return false;}
  return true;
 }
 movePlayer(position,dx,dz){let x=position.x+dx,z=position.z+dz;for(let iter=0;iter<2;iter++)for(const y of[.22,.58,.96,1.34]){const q=this.resolve(x,y,z,.19,null,true);x=q[0];z=q[2];}return{x:Math.max(-3.87*this.scale,Math.min(3.87*this.scale,x)),z:Math.max(-3.02*this.scale,Math.min(3.02*this.scale,z))};}
}
