import {selectedScoreNote,deleteScoreNote,fillStartingMelody,scorePointerAction} from './composer-editing.js';
import {newComposition,validateComposition,PROGRESSIONS,NOTE_NAMES,chordAt,chordName,progression,snapToKey,PART_COLORS,INSTRUMENT_NAMES,activeInstruments,mainInstrument} from './composition.js';
import {scoreLanes,extendScore,quantizeHum} from './music-sheet.js';
import {mountHumming} from './humming.js';
import {CompositionPlayer} from './composition-player.js';
const natural=[0,2,4,5,7,9,11],esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const midiAt=step=>60+Math.floor(step/7)*12+natural[((step%7)+7)%7];
const staffStep=midi=>{let best=0,d=Infinity;for(let i=-12;i<=26;i++){const n=Math.abs(midiAt(i)-midi);if(n<d){d=n;best=i;}}return best;};
export function mountComposer({audio,keyboard,guitars,rig,toast,onStart,onStop,onOpen,onLead,prepare}){
  const draftKey='afterlight-composition-v1'+(new URLSearchParams(location.search).has('qa')?'-qa':'');
  let project=newComposition(),track=0,duration=1,accidental=0,eraser=false,undo=[],drag=null,page=0,allPages=false,hummer=null,humTrack=0,humStart=0,humOpen=false,humSettings=null,selection=null,performPending=false;
  try{const stored=localStorage.getItem(draftKey);if(stored)project=validateComposition(JSON.parse(stored));const editor=JSON.parse(localStorage.getItem(draftKey+'-editor')||'{}');track=Math.max(0,Math.min(3,Number(editor.track)||0));page=Math.max(0,Number(editor.page)||0);allPages=!!editor.allPages;}catch{}
  const player=new CompositionPlayer({audio,keyboard,guitars,onStart,onStop,prepare}),element=document.createElement('section');element.id='composer';element.hidden=true;element.setAttribute('aria-label','Music playground');element.tabIndex=-1;document.querySelector('#app').append(element);
  const mini=document.createElement('div');mini.id='composition-hud';mini.hidden=true;mini.innerHTML='<div><small>ENSEMBLE / LIVE</small><span id="ensemble-clock"></span></div><label>Main <select id="ensemble-lead" aria-label="Main performance instrument"></select></label><button id="ensemble-sheet">Score lanes</button><button id="ensemble-stop">■ Stop</button>';document.querySelector('#app').append(mini);mini.querySelector('#ensemble-stop').onclick=()=>player.stop();mini.querySelector('#ensemble-sheet').onclick=()=>{element.hidden=!element.hidden;if(!element.hidden)draw();};
  mini.querySelector('#ensemble-lead').onchange=e=>setLead(e.target.value);
  const button=document.createElement('button');button.id='composer-button';button.textContent='✎';button.setAttribute('aria-label','Open music playground');document.querySelector('.top-tools').append(button);button.onclick=show;
  function saveDraft(){try{localStorage.setItem(draftKey,JSON.stringify(project));localStorage.setItem(draftKey+'-editor',JSON.stringify({track,page,allPages}));}catch{}}
  function remember(){undo.push(structuredClone(project));if(undo.length>50)undo.shift();}
  function updateSetting(fn){if(hummer?.busy){toast('Finish or cancel humming before changing the score.');return;}selection=null;remember();player.stop();fn();saveDraft();draw();}
  function leadOptions(){const active=activeInstruments(project);return (active.length?active:['keyboard']).map(id=>`<option value="${id}" ${id===mainInstrument(project)?'selected':''}>${INSTRUMENT_NAMES[id]}</option>`).join('');}
  function refreshMini(){mini.querySelector('#ensemble-lead').innerHTML=leadOptions();}
  function setLead(id){project.lead=id;if(player.project)player.project.lead=id;saveDraft();refreshMini();if(player.playing)onLead?.(player.project);}
  function show(){if(!player.playing){onOpen?.();rig.choose('keyboard');}element.hidden=false;document.querySelector('#panel').hidden=true;document.querySelector('#camera-play')?.setAttribute('hidden','');draw();}
  function hide(){element.hidden=true;hummer?.stop();}
  async function perform(){if(performPending)return;if(player.playing){player.stop();draw();return;}hummer?.stop();const b=element.querySelector('#compose-play');if(!activeInstruments(project).length){toast('Drop a note, choose an accompaniment, or try a starting melody.');return;}performPending=true;if(b){b.disabled=true;b.textContent='Preparing sound…';}try{const started=await player.play(project);if(started!==false){element.hidden=true;refreshMini();toast('Performing · '+activeInstruments(project).map(id=>INSTRUMENT_NAMES[id]).join(' + '));}}catch(e){toast(e.message);}finally{performPending=false;draw();}}
  function draw(){
    page=Math.max(0,Math.min(Math.ceil(project.bars/4)-1,page));saveDraft();
    element.innerHTML=`<header class="composer-head"><div><small>AFTERLIGHT / MUSIC PLAYGROUND</small><h2>Make a little music.</h2></div><button id="compose-close" aria-label="Close composer">×</button></header>
    <div class="composer-toolbar"><label>Song <input id="compose-title" maxlength="80" value="${esc(project.title)}"></label><label>Key <select id="compose-key">${NOTE_NAMES.map((n,i)=>`<option value="${i}" ${i===project.key?'selected':''}>${n}</option>`).join('')}</select></label><label>Tempo <input id="compose-bpm" type="number" min="40" max="180" value="${project.bpm}"></label><span class="compose-signature">4/4</span></div>
    <div class="composer-palettes"><label>A feeling <select id="compose-progression">${PROGRESSIONS.map(p=>`<option value="${p.id}" ${p.id===project.progression?'selected':''}>${esc(p.name)} · ${p.roman}</option>`).join('')}</select></label><label>Accompaniment <select id="compose-backing">${[['guitar-0','Cedar guitar'],['keyboard','Keyboard'],['guitar-1','Sage guitar'],['guitar-2','Ivory guitar'],['none','Melody alone']].map(([id,name])=>`<option value="${id}" ${id===project.backing?'selected':''}>${name}</option>`).join('')}</select></label><label>Rhythm <select id="compose-rhythm">${[['steady','Gentle pulse'],['pop','Down / down-up / up-down-up'],['arpeggio','Flowing eighth notes']].map(([id,name])=>`<option value="${id}" ${id===project.rhythm?'selected':''}>${name}</option>`).join('')}</select></label></div>
    <div class="composer-chords">${progression(project).chords.map((_,i)=>`<button data-preview-chord="${i}"><strong>${chordName(chordAt(project,i))}</strong><small>${i+1}</small></button>`).join('')}</div>
    <div class="composer-note-tools"><label>Note <select id="compose-length">${[[.5,'♪ Eighth'],[1,'♩ Quarter'],[2,'𝅗𝅥 Half'],[4,'𝅝 Whole']].map(([v,n])=>`<option value="${v}" ${v===duration?'selected':''}>${n}</option>`).join('')}</select></label><label>Pitch <select id="compose-accidental">${[[0,'Natural'],[1,'♯ Sharp'],[-1,'♭ Flat']].map(([v,n])=>`<option value="${v}" ${v===accidental?'selected':''}>${n}</option>`).join('')}</select></label><label><input id="compose-snap" type="checkbox" ${project.snap?'checked':''}> Keep notes in key</label><button id="compose-eraser" class="${eraser?'selected':''}">Eraser</button><button id="compose-undo" ${undo.length?'':'disabled'}>Undo</button><button id="compose-clear">Clear ${INSTRUMENT_NAMES[project.tracks[track].instrument]}</button></div>
    <div class="score-navigation"><div><button id="score-prev" aria-label="Previous four bars" ${page===0?'disabled':''}>←</button><select id="score-page" aria-label="Score page">${Array.from({length:Math.ceil(project.bars/4)},(_,i)=>`<option value="${i}" ${i===page?'selected':''}>Bars ${i*4+1}–${Math.min(project.bars,i*4+4)}</option>`).join('')}</select><button id="score-next" aria-label="Next four bars" ${page>=Math.ceil(project.bars/4)-1?'disabled':''}>→</button><span>${project.bars} bars</span></div><button id="score-extend" ${project.bars>=128?'disabled':''}>＋ Add 4 bars</button><label><input id="score-all" type="checkbox" ${allPages?'checked':''}> Full sheet</label></div>
    <div class="composer-lane-picker" role="group" aria-label="Choose the lane to edit">${project.tracks.map((t,i)=>`<button data-edit-track="${i}" aria-label="Edit ${INSTRUMENT_NAMES[t.instrument]} lane" aria-pressed="${track===i}" style="--part-color:${PART_COLORS[t.instrument]}"><span></span><strong>${INSTRUMENT_NAMES[t.instrument]}</strong><small>${track===i?'EDITING':t.notes.length+' notes'}</small></button>`).join('')}</div>
    <div id="composer-selection"><span id="editing-target"></span><span id="selected-note-info"></span><button id="compose-delete" disabled>Delete note · ⌫</button></div>
    <section id="hum-controls" ${humOpen?'':'hidden'}><div><strong>Hum into <span id="hum-target">${INSTRUMENT_NAMES[project.tracks[track].instrument]}</span></strong><button id="hum-start">● Start humming</button><button id="hum-cancel" aria-label="Cancel humming">Cancel</button></div><label for="hum-device">Input <select id="hum-device"><option value="">Default microphone</option></select></label><label><input id="hum-append" type="checkbox" checked> Add after the current song</label><div class="hum-monitor"><label>Input level <meter id="hum-level" min="0" max="1" value="0"></meter></label><strong id="hum-pitch">—</strong><span id="hum-notes">0 notes</span></div><p id="hum-status" role="status" aria-live="polite">Microphone off · nothing is uploaded</p><p>Allow the microphone prompt, wait for the two-beat count-in, then hum. Finish to add notes to the named lane. Keep notes in key tunes the replayed notes, not your recorded voice. No audio is uploaded.</p></section>
    <div id="score-systems" class="score-systems"></div>
    <footer class="composer-transport"><button id="compose-play">${player.playing?'■ Stop':'▶ Perform together'}</button><label><input id="compose-loop" type="checkbox" ${project.loop?'checked':''}> Loop</label><label>Main <select id="compose-lead">${leadOptions()}</select></label><button id="compose-seed">Starting melody → ${INSTRUMENT_NAMES[project.tracks[track].instrument]}</button><button id="compose-hum">🎙 Hum into ${INSTRUMENT_NAMES[project.tracks[track].instrument]}</button><button id="compose-save">Save song</button><button id="compose-load">Open song</button><input id="compose-file" type="file" accept=".json,.afterlight" hidden><span id="compose-clock">0:00</span></footer>
    <p class="composer-tip">Choose a lane above, or click its name. Click a blank staff to add a note; click a note to select it; drag to move it; Delete/Backspace removes it. Starting melody fills only empty beats in the selected lane and displayed four bars. Pale accompaniment notes are automatic and not editable. Add bars to keep writing, or choose Full sheet to see every system. Guitar notation is written one octave above its sound. Your draft saves on this device.</p>`;
    const $=id=>element.querySelector('#'+id);$('compose-close').onclick=hide;
    $('compose-title').onchange=e=>{remember();project.title=e.target.value;saveDraft();};
    for(const [id,key,parse]of[['key','key',Number],['bpm','bpm',v=>Math.max(40,Math.min(180,Number(v)||96))],['progression','progression',String],['backing','backing',String],['rhythm','rhythm',String]])$('compose-'+id).onchange=e=>updateSetting(()=>{project[key]=parse(e.target.value);if(key==='progression')project.bars=Math.max(project.bars,progression(project).chords.length);});
    $('compose-length').onchange=e=>duration=Number(e.target.value);$('compose-accidental').onchange=e=>accidental=Number(e.target.value);$('compose-snap').onchange=e=>{project.snap=e.target.checked;saveDraft();};$('compose-loop').onchange=e=>{project.loop=e.target.checked;if(player.project)player.project.loop=project.loop;saveDraft();};$('compose-lead').onchange=e=>setLead(e.target.value);
    $('compose-eraser').onclick=()=>{eraser=!eraser;draw();};$('compose-undo').onclick=()=>{if(!undo.length)return;player.stop();project=undo.pop();selection=null;draw();};$('compose-clear').onclick=()=>updateSetting(()=>project.tracks[track].notes=[]);
    $('compose-play').onclick=perform;$('compose-play').disabled=performPending;$('compose-seed').onclick=()=>{if(hummer?.busy)return;player.stop();remember();const added=fillStartingMelody(project,track,page);if(!added.length)undo.pop();selection=added.length?{track,id:added[0].id}:selection;saveDraft();draw();toast(added.length?added.length+' notes added to '+INSTRUMENT_NAMES[project.tracks[track].instrument]+' · bars '+(page*4+1)+'–'+Math.min(project.bars,page*4+4):'Those beats already have notes. Nothing was replaced.');};
    element.querySelectorAll('[data-edit-track]').forEach(b=>b.onclick=()=>selectLane(Number(b.dataset.editTrack)));$('compose-delete').onclick=deleteSelected;
    $('score-prev').onclick=()=>{page--;draw();};$('score-next').onclick=()=>{page++;draw();};$('score-page').onchange=e=>{page=Number(e.target.value);draw();};$('score-all').onchange=e=>{allPages=e.target.checked;saveDraft();drawStaff();};$('score-extend').onclick=()=>updateSetting(()=>{page=Math.floor(project.bars/4);extendScore(project);});
    element.querySelectorAll('[data-preview-chord]').forEach(b=>b.onclick=()=>previewChord(Number(b.dataset.previewChord)));
    $('compose-save').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(project,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='afterlight-song.afterlight.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('compose-load').onclick=()=>$('compose-file').click();$('compose-file').onchange=async e=>{try{const file=e.target.files[0];if(!file||file.size>2*1024*1024)throw Error('Choose an Afterlight song smaller than 2MB.');const next=validateComposition(JSON.parse(await file.text()));remember();player.stop();project=next;selection=null;page=0;draw();}catch(e){toast(e.message);}};
    $('compose-hum').onclick=()=>{humOpen=true;$('hum-controls').hidden=false;$('hum-controls').scrollIntoView({block:'nearest',behavior:'smooth'});hummer.start();};
    if(!hummer)hummer=mountHumming({element,audio,getSettings:()=>project,getTarget:()=>INSTRUMENT_NAMES[project.tracks[track].instrument],toast,onState:syncEditingChrome,onBeforeStart:()=>{player.stop();onOpen?.();humTrack=track;humSettings=structuredClone(project);humStart=$('hum-append').checked?project.bars*4:page*16;},onCapture:notes=>{remember();const captured=quantizeHum(notes,{startBeat:humStart,bpm:humSettings.bpm,key:humSettings.key,snap:humSettings.snap,minor:!!progression(humSettings).minor,snapNote:snapToKey}),part=project.tracks[humTrack],added=captured.filter(n=>n.beat<512).slice(0,4096-part.notes.length);part.notes.push(...added);if(!added.length){undo.pop();return 'The song or lane is full. No notes were added.';}const end=Math.max(project.bars*4,...added.map(n=>n.beat+n.duration));project.bars=Math.min(128,Math.ceil(end/16)*4);track=humTrack;selection={track,id:added[0].id};page=Math.min(Math.ceil(project.bars/4)-1,Math.floor(humStart/16));humOpen=true;saveDraft();draw();return added.length+' notes added to '+INSTRUMENT_NAMES[part.instrument]+' · press Perform together to hear them.';}});
    else hummer.bind();
    drawStaff();refreshMini();syncEditingChrome();
  }
  function selectLane(index){if(hummer?.busy){toast('Finish humming into '+INSTRUMENT_NAMES[project.tracks[humTrack].instrument]+' before switching lanes.');return;}track=Math.max(0,Math.min(3,index));selection=null;saveDraft();drawStaff();syncEditingChrome();element.focus({preventScroll:true});}
  function deleteSelected(){if(element.hidden||hummer?.busy||!selectedScoreNote(project,selection))return false;remember();player.stop();deleteScoreNote(project,selection);selection=null;saveDraft();drawStaff();syncEditingChrome();return true;}
  function syncEditingChrome(humState){const $=id=>element.querySelector('#'+id);if(!$('editing-target'))return;const busy=humState?.busy??hummer?.busy??false,name=INSTRUMENT_NAMES[project.tracks[track].instrument],note=selectedScoreNote(project,selection);
    $('editing-target').textContent='EDITING · '+name+' · bars '+(page*4+1)+'–'+Math.min(project.bars,page*4+4);$('selected-note-info').textContent=note?'Selected '+NOTE_NAMES[note.midi%12]+(Math.floor(note.midi/12)-1)+' · beat '+(note.beat+1)+' · Delete / Backspace':'Click a note to select it';$('compose-delete').disabled=!note||busy;$('compose-clear').textContent='Clear '+name;$('compose-seed').textContent='Starting melody → '+name;$('compose-hum').textContent=busy?(humState?.phase==='requesting'?'Cancel microphone request':'■ Finish humming'):'🎙 Hum into '+name;$('compose-hum').setAttribute('aria-label',busy?'Finish or cancel humming':'Start microphone and hum into '+name);
    element.querySelectorAll('[data-edit-track]').forEach(b=>{const selected=Number(b.dataset.editTrack)===track;b.setAttribute('aria-pressed',String(selected));b.disabled=busy;b.querySelector('small').textContent=selected?'EDITING':project.tracks[Number(b.dataset.editTrack)].notes.length+' notes';});
    for(const id of ['compose-key','compose-bpm','compose-progression','compose-backing','compose-rhythm','compose-clear','compose-seed','compose-undo','hum-append'])if($(id))$(id).disabled=busy||(id==='compose-undo'&&!undo.length);
  }
  function systemMarkup(firstBar){const firstBeat=firstBar*4,count=Math.min(4,project.bars-firstBar)*4,w=820/count,lanes=scoreLanes(project,firstBar,4);let content='';
    for(const lane of lanes){const offset=lane.index*158,guitar=lane.instrument!=='keyboard';content+=`<g data-lane="${lane.index}" transform="translate(0 ${offset})" style="--part-color:${lane.color}"><rect class="staff-lane ${track===lane.index?'editing-lane':''}" x="0" y="0" width="960" height="155"/><text x="17" y="17" class="lane-name" data-lane-select="${lane.index}" role="button" tabindex="0" aria-label="Edit ${esc(lane.name)} lane">${esc(lane.name)}${track===lane.index?' · EDITING':''}</text><text x="18" y="106" class="staff-clef">𝄞</text>`;
      for(const y of[60,70,80,90,100])content+=`<path d="M75 ${y}H920" class="staff-line"/>`;for(let b=0;b<=count;b++)content+=`<path d="M${86+b*w} 45V134" class="${b%4?'beat-line':'bar-line'}"/>${b%4?'':`<text x="${90+b*w}" y="148" class="staff-bar">${firstBar+b/4+1}</text>`}`;
      function note(n,backing=false){const written=n.midi+(guitar?12:0),step=staffStep(written),x=86+(Math.max(n.beat,firstBeat)-firstBeat)*w,y=110-step*5;let out=`<g ${backing?'class="staff-backing"':`data-note="${esc(n.id)}" class="staff-note ${selection?.track===lane.index&&selection?.id===n.id?'selected-note':''}" role="button" tabindex="0" aria-pressed="${selection?.track===lane.index&&selection?.id===n.id}" aria-label="Select ${NOTE_NAMES[n.midi%12]}${Math.floor(n.midi/12)-1} note in ${esc(lane.name)}, beat ${n.beat+1}"`}><title>${NOTE_NAMES[n.midi%12]}${Math.floor(n.midi/12)-1}, beat ${n.beat+1}${backing?', accompaniment':''}</title>`;for(let line=110;line<=y&&line<150;line+=10)out+=`<path d="M${x-10} ${line}h20" class="staff-ledger"/>`;for(let line=50;line>=y&&line>15;line-=10)out+=`<path d="M${x-10} ${line}h20" class="staff-ledger"/>`;const a=written-midiAt(step);if(a)out+=`<text x="${x-18}" y="${y+4}" class="staff-accidental">${a>0?'♯':'♭'}</text>`;out+=`<path d="M${x} ${Math.min(127,Math.max(26,y+9))}h${Math.max(3,Math.min(n.duration-Math.max(0,firstBeat-n.beat),count-Math.max(0,n.beat-firstBeat))*w-4)}" class="note-length"/><ellipse cx="${x}" cy="${y}" rx="6" ry="4" transform="rotate(-18 ${x} ${y})" class="${n.duration>=2?'open-note':'filled-note'}"/>`;if(n.duration<4){out+=`<path d="M${x+5} ${y}v-27" class="note-stem"/>`;if(n.duration<1)out+=`<path d="M${x+5} ${y-27}q15 8 4 18" class="note-stem"/>`;}if(!backing&&selection?.track===lane.index&&selection?.id===n.id)out+=`<ellipse class="note-selection-ring" cx="${x}" cy="${y}" rx="11" ry="9"/>`;if(n.beat<firstBeat)out+=`<path d="M${x-11} ${y+9}q11 9 22 0" class="note-stem"/>`;return out+'</g>';}
      for(const e of lane.backing){if(e.label)content+=`<text x="${86+(e.beat-firstBeat)*w}" y="36" class="backing-chord">${e.label}</text>`;for(const midi of e.midis)content+=note({...e,midi},true);}for(const n of lane.notes)content+=note(n);content+='</g>';
    }return content+`<path data-playhead="${firstBar}" d="M86 24V615" class="compose-playhead"/>`;
  }
  function drawStaff(){const container=element.querySelector('#score-systems');if(!container)return;const pages=allPages?Array.from({length:Math.ceil(project.bars/4)},(_,i)=>i):[page];container.innerHTML=pages.map(i=>`<section class="score-system"><div class="system-caption">SYSTEM ${i+1} / ${Math.ceil(project.bars/4)} <span>Bars ${i*4+1}–${Math.min(project.bars,i*4+4)} · aligned ensemble</span></div><div class="staff-scroll"><svg data-score-page="${i}" viewBox="0 0 960 632" role="group" aria-label="All instrument score lanes, bars ${i*4+1} to ${Math.min(project.bars,i*4+4)}">${systemMarkup(i*4)}</svg></div></section>`).join('');
    for(const svg of container.querySelectorAll('svg')){const firstBar=Number(svg.dataset.scorePage)*4,count=Math.min(4,project.bars-firstBar)*4,w=820/count;
      const locate=e=>{const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform(svg.getScreenCTM().inverse()),lane=Math.max(0,Math.min(3,Math.floor(q.y/158))),localY=q.y-lane*158;let midi=midiAt(Math.max(-5,Math.min(18,Math.round((110-localY)/5))))+accidental-(lane?12:0);if(project.snap)midi=snapToKey(midi,project.key,!!progression(project).minor);return{lane,x:q.x,localY,beat:firstBar*4+Math.max(0,Math.min(count-.25,Math.round((q.x-86)/w*4)/4)),midi};};
      svg.onpointerdown=e=>{if(e.button!==0||player.playing||hummer?.busy)return;const id=e.target.closest('[data-note]')?.dataset.note,pos=locate(e),action=scorePointerAction({noteId:id,x:pos.x,localY:pos.localY,eraser});track=pos.lane;element.focus({preventScroll:true});
        if(action==='select-lane'){selectLane(track);return;}let n=project.tracks[track].notes.find(n=>n.id===id);if(action==='delete'){selection=n?{track,id:n.id}:null;deleteSelected();return;}
        if(action==='add-note'){if(project.tracks[track].notes.length>=4096)return;remember();n={id:crypto.randomUUID(),beat:pos.beat,midi:pos.midi,duration,velocity:.65};project.tracks[track].notes.push(n);}if(!n)return;selection={track,id:n.id};drag={id:n.id,lane:track,startX:e.clientX,startY:e.clientY,moving:false,added:action==='add-note'};svg.setPointerCapture(e.pointerId);player.previewNote(n.midi,project.tracks[track].instrument).catch(e=>toast(e.message));svg.innerHTML=systemMarkup(firstBar);saveDraft();syncEditingChrome();};
      svg.onpointermove=e=>{if(!drag)return;const n=project.tracks[drag.lane].notes.find(n=>n.id===drag.id),pos=locate(e);if(!n||pos.lane!==drag.lane)return;if(!drag.moving&&Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)<4)return;if(!drag.moving&&!drag.added)remember();drag.moving=true;n.beat=pos.beat;n.midi=pos.midi;svg.innerHTML=systemMarkup(firstBar);syncEditingChrome();};svg.onpointerup=()=>{drag=null;saveDraft();drawStaff();syncEditingChrome();};svg.onpointercancel=()=>{drag=null;saveDraft();};
      svg.onkeydown=e=>{const lane=e.target.closest('[data-lane-select]')?.dataset.laneSelect,id=e.target.closest('[data-note]')?.dataset.note;if(e.code==='Enter'&&lane!==undefined){e.preventDefault();selectLane(Number(lane));}else if(e.code==='Enter'&&id){e.preventDefault();const index=Number(e.target.closest('[data-lane]')?.dataset.lane);track=index;selection={track,id};drawStaff();syncEditingChrome();element.focus({preventScroll:true});}};

    }
  }
  async function previewChord(index,direction=1,velocity=.65){try{await player.previewChord(project,index,direction,velocity);}catch(e){toast(e.message);}}
  document.querySelector('#musicbook-button').addEventListener('click',()=>player.stop(),{capture:true});document.querySelector('#play-button').addEventListener('click',()=>player.stop(),{capture:true});
  addEventListener('keydown',e=>{if(element.hidden&&!player.playing)return;if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.target.isContentEditable)return;if((e.code==='Delete'||e.code==='Backspace')&&!element.hidden){e.preventDefault();e.stopImmediatePropagation();deleteSelected();}else if(e.code==='Escape'&&selection&&!element.hidden){e.preventDefault();e.stopImmediatePropagation();selection=null;drawStaff();syncEditingChrome();}else if(e.code==='Escape'){player.stop();hide();rig.choose('sofa');}else if(e.code==='Space'){e.preventDefault();e.stopImmediatePropagation();perform();}else if((e.ctrlKey||e.metaKey)&&e.code==='KeyZ'&&undo.length){e.preventDefault();player.stop();project=undo.pop();selection=null;draw();}},{capture:true});
  return{show,hide,player,setLead,loadProject(value){player.stop();remember();project=validateComposition(value);selection=null;page=0;saveDraft();draw();},previewChord,setProgression(id){if(!PROGRESSIONS.some(p=>p.id===id))return;updateSetting(()=>{project.progression=id;project.bars=Math.max(project.bars,progression(project).chords.length);});},get project(){return project;},get editing(){return{track,lane:INSTRUMENT_NAMES[project.tracks[track].instrument],selectedNote:selection?.id||null,humming:hummer?.state||null};},get visible(){return !element.hidden;},update(){player.update();mini.hidden=!player.playing;mini.querySelector('#ensemble-clock').textContent=project.title+' · bar '+Math.floor(player.beat/4+1)+' / '+project.bars;if(element.hidden)return;for(const line of element.querySelectorAll('[data-playhead]')){const first=Number(line.dataset.playhead)*4,count=Math.min(16,project.bars*4-first),beat=player.beat-first;line.style.display=player.playing&&beat>=0&&beat<count?'':'none';line.setAttribute('d',`M${86+beat*820/count} 24V615`);}const clock=element.querySelector('#compose-clock');if(clock)clock.textContent=Math.floor(player.elapsed/60)+':'+String(Math.floor(player.elapsed%60)).padStart(2,'0');},dispose(){hummer?.stop();saveDraft();hummer?.dispose();player.stop();}};
}
