import * as THREE from 'three/webgpu';import {uniform,texture,color} from 'three/tsl';import {box,label} from './geometry.js';import {mat,palette as P} from './materials.js';
export function environmentControls({scene,room,sun,fill,hemi,renderer,breeze}){let mode='golden',transition=0,concert=0,concertTarget=0;const lights=[];room.root.traverse(o=>{if(o.isPointLight)lights.push({light:o,base:o.intensity,kind:o.position.x<-3?'desk':'fairy'});});const display=room.display,displayPower=uniform(1);if(display)display.material.colorNode=texture(display.material.map).mul(displayPower);
 const bulbs=[];room.root.traverse(o=>{if(o.isMesh&&o.userData.roomLight==='fairy'){const u=uniform(1);o.material.emissiveNode=color('#ffce8f').mul(u).mul(3);bulbs.push(u);}});
 const city=new THREE.SpotLight('#819bd6',0,8,1.03,.75,2);city.position.set(-3.20,1.57,-.45);city.target.position.set(.8,.6,-.4);scene.add(city,city.target);const neonBlue=new THREE.PointLight('#88caff',0,5,2);neonBlue.position.set(-3.2,1.30,.45);scene.add(neonBlue);const neonPink=new THREE.PointLight('#ba78a5',0,5,2);neonPink.position.set(-3.2,2.08,-1.28);scene.add(neonPink);
 const stage=new THREE.SpotLight('#9bd1ff',0,5,.73,.68,2);stage.position.set(-1.2,2.62,-.7);stage.target.position.set(-1.27,.9,-1.59);scene.add(stage,stage.target);const stageRim=new THREE.PointLight('#c594d9',0,3.6,2);stageRim.position.set(-.45,1.3,-1.8);scene.add(stageRim);
 const settings={desk:true,fairy:true,monitor:true};const presets={golden:{time:'17:42',label:'GOLDEN HOUR',sun:3.10,hemi:.46,fill:.21,exposure:1.03,env:.16,city:0,neon:0,sky:['#91a7c5','#ebb6a0','#f4ca8d'],sunColor:'#ffc68b',sunPosition:[-6,4.6,7]},blue:{time:'18:24',label:'BLUE HOUR',sun:.10,hemi:.20,fill:.05,exposure:1.0,env:.07,city:14,neon:1.8,sky:['#283e69','#686da0','#c38a9e'],sunColor:'#b79fca',sunPosition:[-6,.4,0]},city:{time:'21:08',label:'CITY LIGHTS ONLY',sun:0,hemi:.025,fill:0,exposure:1.12,env:.024,city:26,neon:3.8,sky:['#0d1734','#172747','#384761'],sunColor:'#839ad1',sunPosition:[-6,-1.0,0]}};
 function sky(colors){const tex=room.sky;if(!tex)return;const c=tex.image.getContext('2d'),w=tex.image.width,h=tex.image.height,g=c.createLinearGradient(0,0,0,h);colors.forEach((x,i)=>g.addColorStop(i/2,x));c.fillStyle=g;c.fillRect(0,0,w,h);tex.needsUpdate=true;}
 function setMode(next){mode=next;const p=presets[next];transition=0;sky(p.sky);sun.color.set(p.sunColor);sun.position.set(...p.sunPosition);hemi.color.set(next==='golden'?'#aab9d9':'#8199cd');hemi.groundColor.set(next==='golden'?'#71585f':'#3b315c');if(next==='city')Object.keys(settings).forEach(k=>settings[k]=false);document.querySelector('.game-clock').innerHTML=p.time+' <span>'+(next==='golden'?'夕暮れ':next==='blue'?'薄明':'夜')+'</span><small>'+p.label+'</small>';}
 const plate=box(room.root,[.026,.20,.12],[4.066,1.44,.30],mat('#e5d4bf'),.008);plate.userData.action='lights';box(room.root,[.032,.086,.064],[4.046,1.45,.30],P.cream,.006);label(room.root,'LIGHTS',.074,.019,[4.025,1.366,.30],{color:'#8e8471',rot:[0,-Math.PI/2,0]});
 const $=s=>document.querySelector(s);const envButton=document.createElement('button');envButton.id='ambience-button';envButton.textContent='☼';envButton.setAttribute('aria-label','Time and room lights');$('.top-tools').prepend(envButton);
 function show(){const panel=$('#panel');panel.hidden=false;panel.innerHTML='<button class="close" aria-label="Close environment controls">×</button><small>THE LIGHT IN HERE</small><h2>An hour to yourself</h2><p>Let the afternoon stay, or watch the city take over.</p><div class="button-row"><button data-time="golden">Golden hour</button><button data-time="blue">Blue hour</button><button data-time="city">City lights</button></div>'+['desk','fairy','monitor'].map(k=>'<div class="control-row"><label for="light-'+k+'">'+({desk:'Desk lamp',fairy:'String lights',monitor:'Studio monitor'}[k])+'</label><input type="checkbox" id="light-'+k+'" '+(settings[k]?'checked':'')+'></div>').join('')+'<div class="button-row"><button id="all-lights-off">All room lights off</button><button id="all-lights-on">All lights on</button></div><h3>A little fresh air</h3><div class="control-row"><label for="open-window">Window open</label><input type="checkbox" id="open-window" '+(breeze.open?'checked':'')+'></div><p class="view-note">Open window: pinned translucent linen responds to gusts, gravity, cloth constraints, and solid-room collision. Closing the casement stops the wind and lets the curtains settle.</p><h3>Cinematic view</h3><p class="view-note"><span class="kbd">H</span> hides the HUD for clean frames. The room opens at sofa eye level; use <span class="kbd">V</span> for a wide cutaway composition.</p>';
 panel.querySelector('.close').onclick=()=>panel.hidden=true;panel.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{setMode(b.dataset.time);show();});for(const k of Object.keys(settings))$('#light-'+k).onchange=e=>settings[k]=e.target.checked;$('#all-lights-off').onclick=()=>{Object.keys(settings).forEach(k=>settings[k]=false);show();};$('#all-lights-on').onclick=()=>{Object.keys(settings).forEach(k=>settings[k]=true);show();};$('#open-window').onchange=()=>breeze.toggle();}
 envButton.onclick=show;setMode('golden');return{settings,show,setMode,setConcert(value){concertTarget=value?1:0;},get concert(){return concert;},get mode(){return mode;},toggleAll(){const on=Object.values(settings).some(Boolean);Object.keys(settings).forEach(k=>settings[k]=!on);},update(dt){const p=presets[mode],a=1-Math.exp(-dt*2);concert+=(concertTarget-concert)*a;const dim=1-concert*.92;stage.intensity=concert*22;stageRim.intensity=concert*3.5;sun.intensity+=(p.sun*(1-concert*.997)-sun.intensity)*a;hemi.intensity+=(p.hemi*dim-hemi.intensity)*a;fill.intensity+=(p.fill*dim-fill.intensity)*a;scene.environmentIntensity+=(p.env*dim-scene.environmentIntensity)*a;renderer.toneMappingExposure+=(p.exposure-renderer.toneMappingExposure)*a;city.intensity+=(p.city-city.intensity)*a;neonBlue.intensity+=(p.neon-neonBlue.intensity)*a;neonPink.intensity+=(p.neon*.66-neonPink.intensity)*a;for(const l of lights)l.light.intensity+=(settings[l.kind]?l.base*dim-l.light.intensity:-l.light.intensity)*a;for(const u of bulbs)u.value+=((settings.fairy?dim:0)-u.value)*a;displayPower.value+=((settings.monitor?dim:.01)-displayPower.value)*a;}};
}
