import {displayedDevelopmentSeconds} from './development-time.js';
export function mountLedger(){const el=document.createElement('div');el.id='dev-ledger';el.innerHTML='<div class="ledger-model">GPT 6.1 SOL <b>MAX</b> <span>STANDARD · NO FAST</span></div><div class="ledger-stats"><div><small>ACTIVE BUILD</small><strong id="build-time">00:00:00</strong></div><div><small>MEASURED TOKENS</small><strong id="build-tokens">—</strong></div><div><small>API EST. / USD</small><button id="build-cost" aria-label="Show token and cost breakdown">—</button></div><button id="capture-button" title="Save a clean development frame" aria-label="Capture development frame">⊞</button></div><div class="ledger-asof" id="ledger-asof">Waiting for the session ledger</div>';document.querySelector('#app').append(el);const detail=document.createElement('section');detail.id='accounting-details';detail.hidden=true;detail.setAttribute('aria-label','Token and cost breakdown');document.querySelector('#app').append(detail);let latest=null;
 const duration=s=>[Math.floor(s/3600),Math.floor(s/60)%60,Math.floor(s)%60].map(x=>String(x).padStart(2,'0')).join(':');
 const draw=()=>{if(!latest)return;const u=latest,t=u.tokens||{},b=u.cost_breakdown||{};const time=u.development_time;detail.innerHTML='<button class="accounting-close" aria-label="Close cost breakdown">×</button><small>MEASURED BUILD USAGE · MAIN + DELEGATED AGENTS</small><h3>Cache-aware accounting</h3>'+ (time?'<p><b>Active build '+duration(displayedDevelopmentSeconds(time))+'</b> · elapsed '+duration(time.elapsed_seconds)+' · idle excluded '+duration(time.idle_seconds)+'</p><p>'+time.method+' This is active-task time, not an estimate of keystroke time.</p>':'')+'<dl><dt>Input, total</dt><dd>'+Number(t.input_tokens||0).toLocaleString()+'</dd><dt>Cached input, subset</dt><dd>'+Number(t.cached_input_tokens||0).toLocaleString()+'</dd><dt>Output incl. reasoning</dt><dd>'+Number(t.output_tokens||0).toLocaleString()+'</dd><dt>Uncached input cost</dt><dd>$'+Number(b.uncached_input_usd||0).toFixed(4)+'</dd><dt>Cached input cost</dt><dd>$'+Number(b.cached_input_usd||0).toFixed(4)+'</dd><dt>Cache writes</dt><dd>$'+Number(b.cache_write_usd||0).toFixed(4)+'</dd><dt>Output cost</dt><dd>$'+Number(b.output_usd||0).toFixed(4)+'</dd></dl><p>Standard, per 1M: $2 uncached input · $0.10 cached input · $10 output. Long-context rates applied per prompt if &gt;272K. Reasoning is not charged twice.</p><p>API-equivalent estimate, not an invoice or subscription credit deduction. Includes completed steps only. Main and explicitly delegated agents are counted once each.</p><p>ImageGen reference charges are not exposed by these logs: excluded, not assumed free.</p>';detail.querySelector('button').onclick=()=>detail.hidden=true;};
 el.querySelector('#build-cost').onclick=()=>{draw();detail.hidden=!detail.hidden;};
 const live=import.meta.env.DEV;
 // The dev server serves the live session ledger; a production build publishes its recorded snapshot as usage.json
 // (vite.config.js) and shows it as recorded, without extrapolating past the snapshot.
 const tick=()=>{const s=displayedDevelopmentSeconds(latest?.development_time,live?Date.now():Date.parse(latest?.development_time?.as_of));document.querySelector('#build-time').textContent=s===null?'—':duration(s);};setInterval(tick,1000);tick();let poll;const refresh=async()=>{try{const r=await fetch(live?'/__dev/usage':import.meta.env.BASE_URL+'usage.json'),u=await r.json();if(u.unavailable)return;latest=u;if(!live)clearInterval(poll);tick();document.querySelector('#build-tokens').textContent=(u.tokens?.total_tokens??0).toLocaleString();document.querySelector('#build-cost').textContent='$'+u.api_equivalent_usd.toFixed(4);const t=new Date(u.usage_as_of);document.querySelector('#ledger-asof').textContent='Recorded '+t.toLocaleTimeString('en-GB',{timeZone:'Asia/Tokyo'})+' JST · cache included · '+(u.sources?.length||1)+' agent'+((u.sources?.length||1)>1?'s':'');el.title='Measured primary + delegated-agent input and output, including re-sent/cached context. Image generation charges unavailable and excluded. Click USD for the cached/uncached breakdown. Last completed step only; in-flight output is not yet counted.';if(!detail.hidden)draw();}catch{document.querySelector('#ledger-asof').textContent=live?'Session ledger requires the local dev server':'Build ledger unavailable';}};refresh();poll=setInterval(()=>{if(!new URLSearchParams(location.search).has('benchmark'))refresh();},20000);return el;}
