import {frequency} from './mechanics.js';
/** Original deterministic arrangements, generated off the main thread. */
function arrangement(record,side=0){const sr=22050,duration=record.duration,data=new Float32Array(Math.ceil(duration*sr)),beat=60/record.bpm;
 const add=(midi,t,len,gain,kind=0)=>{const start=Math.floor(t*sr),count=Math.min(Math.floor(len*sr),data.length-start),f=frequency(midi);if(count<=0)return;const h=[];for(let n=1;n<=4;n++){const omega=2*Math.PI*f*n*Math.sqrt(1+.00006*n*n)/sr;h.push({s:0,c:1,ds:Math.sin(omega),dc:Math.cos(omega),a:(n===1?1:.7)/(n*n)});}let decay=1,attack=1;const decayStep=Math.exp(-(kind?1.6:2.3)/sr),attackStep=Math.exp(-300/sr);for(let i=0;i<count;i++){let v=0;for(let n=0;n<4;n++){const o=h[n],ns=o.s*o.dc+o.c*o.ds;o.c=o.c*o.dc-o.s*o.ds;o.s=ns;v+=o.s*o.a;}data[start+i]+=v*(1-attack)*decay*gain;decay*=decayStep;attack*=attackStep;}};
 const minor=record.id==='paper'||record.id==='rain',triad=minor?[0,3,7]:[0,4,7],roots=[0,minor?5:9,minor?8:5,7];const bars=Math.ceil(duration/(beat*4));const renderBar=bar=>{const index=(bar+side*2)%4,root=record.root+roots[index]-12,triad=minor?(index<2?[0,3,7]:[0,4,7]):index===1?[0,3,7]:[0,4,7];add(root-12,bar*beat*4,beat*3.8,.047,1);for(let b=0;b<8;b++)add(root+triad[(b+bar%3)%3]+(b%4===3?12:0),bar*beat*4+b*beat*.5,beat*2.6,.026+Math.sin(bar*.7)*.003);if(bar%4>=1){const melody=[12,14,minor?15:16,19,16,14,12,7];for(let b=0;b<4;b++)add(record.root+melody[(bar*3+b+side*3)%8],(bar*4+b+.08)*beat,beat*1.7,.019);}}
 const finish=()=>{for(let i=0;i<data.length;i++)data[i]*=Math.min(1,i/sr/2,(data.length-i)/sr/3);return{data,sampleRate:sr,duration};};return{bars,renderBar,finish};}
export function compose(record,side=0){const a=arrangement(record,side);for(let bar=0;bar<a.bars;bar++)a.renderBar(bar);return a.finish();}
/** Resilient same-device fallback. Yield between small batches instead of freezing the game. */
export async function composeAsync(record,side=0,{yieldTask=()=>new Promise(resolve=>setTimeout(resolve,0)),cancelled=()=>false}={}){const a=arrangement(record,side);for(let bar=0;bar<a.bars;bar++){if(cancelled())throw Error('Record generation cancelled.');a.renderBar(bar);if(bar%2===1)await yieldTask();}return a.finish();}

