import {hasPerf,onPerformanceOptions} from './runtime-performance.js';
import * as THREE from 'three/webgpu';import {pass,uv,vec4,vec3,vec2,float,mix,renderOutput,uniform,Fn,If,smoothstep} from 'three/tsl';import {bloom} from 'three/addons/tsl/display/BloomNode.js';import {ao} from 'three/addons/tsl/display/GTAONode.js';import {fxaa} from 'three/addons/tsl/display/FXAANode.js';import {gaussianBlur} from 'three/addons/tsl/display/GaussianBlurNode.js';
export function atmosphere(renderer,scene,camera,{software=false}={}){const pipeline=new THREE.RenderPipeline(renderer),scenePass=pass(scene,camera,{samples:0}),base=scenePass.getTextureNode('output'),depth=scenePass.getTextureNode('depth');
 // Sampling/gathering a multisampled depth texture is invalid on WebGPU. The post pass explicitly resolves AA with FXAA instead.
 const foregroundCamera=camera.clone(),foreground=pass(scene,foregroundCamera,{samples:0});const heroLayers=new THREE.Layers();heroLayers.set(1);foreground.setLayers(heroLayers);const hero=foreground.getTextureNode('output');let foregroundRoot=null,foregroundDirty=true,originalLayers=new Map();scene.traverse(o=>{if(o.isLight)o.layers.enable(1);});const renderForeground=foreground.updateBefore.bind(foreground),clearColor=new THREE.Color();foreground.updateBefore=frame=>{if(!foregroundRoot&&!foregroundDirty)return;foregroundCamera.copy(camera);foregroundCamera.layers.set(1);const background=scene.background,backgroundNode=scene.backgroundNode,alpha=renderer.getClearAlpha();renderer.getClearColor(clearColor);try{scene.background=null;scene.backgroundNode=null;renderer.setClearColor(0,0);renderForeground(frame);foregroundDirty=false;}finally{scene.background=background;scene.backgroundNode=backgroundNode;renderer.setClearColor(clearColor,alpha);}};
 const occlusion=ao(depth,null,camera);occlusion.resolutionScale=.5;occlusion.radius.value=.26;occlusion.thickness.value=.5;occlusion.samples.value=8;
 const focus=uniform(1.3),aperture=uniform(0),isolation=uniform(0),pixel=uniform(new THREE.Vector2(1/innerWidth,1/innerHeight));
 const defocused=gaussianBlur(base,vec2(2.4),4,{resolutionScale:.5});
 let warming=false;const updateBlur=defocused.updateBefore.bind(defocused);defocused.updateBefore=frame=>{if(warming||isolation.value>.001)updateBlur(frame);};
 const lens=Fn(()=>{const rgb=base.rgb.toVar();If(aperture.greaterThan(.01),()=>{
  const radius=scenePass.getViewZNode().negate().sub(focus).abs().div(focus.mul(.6)).clamp(0,1).mul(aperture);let sum=base.rgb;
  for(const [x,y] of [[1,0],[-1,0],[0,1],[0,-1],[.707,.707],[-.707,.707],[.707,-.707],[-.707,-.707]])sum=sum.add(base.sample(uv().add(pixel.mul(vec2(x,y)).mul(radius))).rgb);
  rgb.assign(sum.div(9));
 });If(isolation.greaterThan(.001),()=>{
  // The guitar's entire depth envelope remains unblurred; only pixels outside it blend to the soft room.
  const coc=smoothstep(float(.20),float(.64),scenePass.getViewZNode().negate().sub(focus).abs());rgb.assign(mix(rgb,defocused.rgb,coc.mul(isolation)));
 });return rgb;})();
 const foregroundVisible=uniform(1);
 const softAO=software?float(1):mix(float(.60),float(1),occlusion),bloomNode=bloom(base,.10,.32,2.1),vignette=float(1).sub(uv().sub(.5).length().pow(2).mul(.14));const rgb=lens.mul(softAO).add(bloomNode.rgb).mul(vignette);const finalRGB=Fn(()=>{const output=vec3(rgb).toVar();If(foregroundVisible.greaterThan(.5),()=>output.assign(mix(output,hero.rgb,hero.a)));return output;})();
 const originalOutput=fxaa(renderOutput(vec4(mix(vec3(rgb),hero.rgb,hero.a),base.a))),branchedOutput=fxaa(renderOutput(vec4(finalRGB,base.a)));
 function selectOutput(){const next=hasPerf('foreground_branch')?branchedOutput:originalOutput;if(pipeline.outputNode!==next){pipeline.outputNode=next;pipeline.needsUpdate=true;}}
 const unsubscribe=onPerformanceOptions(selectOutput);selectOutput();pipeline.outputColorTransform=false;pipeline.focusAt=(distance,amount,isolated=0,dt=1/60)=>{foregroundVisible.value=hasPerf('foreground_branch')?(foregroundRoot?1:0):1;focus.value=Math.max(.15,distance);aperture.value=amount;isolation.value+=(isolated-isolation.value)*(1-Math.exp(-dt*4));pixel.value.set(1/(innerWidth*renderer.getPixelRatio()),1/(innerHeight*renderer.getPixelRatio()));};pipeline.setForeground=root=>{if(root===foregroundRoot)return;for(const [o,mask]of originalLayers)o.layers.mask=mask;originalLayers.clear();foregroundRoot=root;foregroundDirty=true;foregroundVisible.value=hasPerf('foreground_branch')?(root?1:0):1;if(root)root.traverse(o=>{originalLayers.set(o,o.layers.mask);o.layers.set(1);});};pipeline.warmForeground=async root=>{const culling=new Map();pipeline.setForeground(root);root.traverse(o=>{if(o.isMesh){culling.set(o,o.frustumCulled);o.frustumCulled=false;}});foregroundCamera.copy(camera);foregroundCamera.layers.set(1);try{await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));}finally{for(const [o,cull]of culling)o.frustumCulled=cull;pipeline.setForeground(null);}};pipeline.foregroundState=()=>({active:!!foregroundRoot,name:foregroundRoot?.name||null});pipeline.warmEffects=async()=>{warming=true;try{await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));}finally{warming=false;}};pipeline.releaseEffects=()=>{unsubscribe();for(const effect of[scenePass,foreground,occlusion,bloomNode,defocused])effect.dispose();pipeline.dispose();};return pipeline;}
