import {CompositionPlayer} from './composition-player.js';
import {compositionEvents,PART_COLORS,INSTRUMENT_NAMES,chordAt,chordName} from './composition.js';
import {tourComposition,TOUR_ENTRANCES} from './tour-score.js';
/** Camera chapters cue entrances; all musical notes follow the actual stylus transport. */
export function musicalTour({audio,model,keyboard,guitars,rig,ui,composer,guitarPresentation,env,breeze,toast,warmup=async()=>{},playerFactory=options=>new CompositionPlayer(options)}){
  const project=tourComposition(),events=compositionEvents(project),player=playerFactory({audio,keyboard,guitars,scoreGroup:'tour',keyOwner:'tour'});player.project=project;player.events=events;
  let generation=0,active=false,preparing=false,index=0,guitar=false,keys=false,wasTour=false,preparePhase='off',cameraEnded=false,cycle=0,scoreRevision=null;
  const finale=document.createElement('section');finale.id='tour-finale';finale.hidden=true;finale.innerHTML='<small>THE AFTERLIGHT SESSION</small><h2>Now it’s your turn.</h2><p>A song can start with one note.</p><div><button id="tour-my-song">Open my music sheet</button><button id="tour-demo-song">Start with this song</button><button id="tour-finale-close" aria-label="Close tour invitation">×</button></div>';document.querySelector('#app').append(finale);
  const sheet=document.createElement('aside');sheet.id='tour-score-preview';sheet.hidden=true;sheet.setAttribute('aria-label','Tour ensemble score');document.querySelector('#app').append(sheet);
  finale.querySelector('#tour-my-song').onclick=()=>{finale.hidden=true;composer.show();};finale.querySelector('#tour-demo-song').onclick=()=>{finale.hidden=true;composer.loadProject(project);composer.show();};finale.querySelector('#tour-finale-close').onclick=()=>finale.hidden=true;
  async function start(){const token=++generation;player.stop();cameraEnded=false;cycle=0;scoreRevision=null;composer.player.stop();composer.hide();finale.hidden=true;sheet.hidden=true;preparing=true;preparePhase='audio';active=false;index=0;guitar=false;keys=false;try{rig.tour.start();rig.tour.paused=true;await audio.resume();if(token!==generation)return;preparePhase='record';const ready=await ui.prepareTourRecord();if(token!==generation||rig.mode!=='tour')return;if(!ready)throw Error('The tour record could not be prepared.');await audio.ensureRecord();if(token!==generation)return;preparePhase='strings';await audio.prepareGuitarBuffers(events,guitars,{cancelled:()=>token!==generation});if(token!==generation)return;preparePhase='visuals';player.projection.warm();player.guides.forEach(g=>g.warm());await warmup();player.projection.root.visible=false;player.guides.forEach(g=>g.hide());if(token!==generation||rig.mode!=='tour')return;model.setSpeed(33+1/3);model.pitch=0;model.seek(0);model.placeArm();model.start();model.setCue(false);player.stop();player.project=project;player.events=events;active=true;preparing=false;preparePhase='ready';rig.tour.time=0;rig.tour.paused=false;toast('Blue hour · original music, with instruments joining in.');}catch(e){if(token===generation){preparing=false;preparePhase='error';rig.choose('sofa',true);toast('Tour sound: '+e.message);}}}
  function finishCamera(){cameraEnded=true;preparing=false;guitarPresentation.release();env.setConcert(false);breeze.setClosed(false);player.projection.root.visible=false;sheet.hidden=true;finale.hidden=false;}
  function stop(completed=false){if(completed){finishCamera();return;}generation++;active=false;preparing=false;cameraEnded=false;preparePhase='off';player.stop();model.stop();model.setCue(true);audio.setVolume(audio.volume);guitarPresentation.release();env.setConcert(false);breeze.setClosed(false);sheet.hidden=true;}
  document.querySelector('[data-view="tour"]').addEventListener('click',start);addEventListener('keydown',e=>{if(e.code==='KeyF'&&!/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)&&!e.target.closest?.('#composer,#camera-play')&&rig.mode!=='keyboard'&&rig.mode!=='concert')start();});
  function preview(){const beat=model.transport*project.bpm/60,first=Math.floor(beat/16)*16,tuning=[40,45,50,55,59,64],naturals=[0,2,4,5,7,9,11];let markup='<small>THE SONG, COMING TOGETHER · BARS '+(first/4+1)+'–'+Math.min(project.bars,first/4+4)+'</small><svg viewBox="0 0 600 194" role="img" aria-label="Aligned guitar and keyboard music staves">';for(const [row,instrument]of ['guitar-0','keyboard'].entries()){const top=45+row*84,base=top+40;markup+='<text x="10" y="'+(top-19)+'">'+INSTRUMENT_NAMES[instrument]+'</text><text x="80" y="'+(top+33)+'" class="tour-clef">𝄞</text>';for(let i=0;i<5;i++)markup+='<path d="M120 '+(top+i*8)+'H588"/>';for(let b=0;b<=16;b+=4)markup+='<path d="M'+(120+b*29)+' '+(top-8)+'V'+(top+38)+'"/>';
      for(const e of events){if(e.instrument!==instrument||e.beat<first||e.beat>=first+16||e.beat>beat+3)continue;const x=120+(e.beat-first)*29,midi=instrument==='keyboard'?e.midi:tuning[e.string]+e.fret+12,octave=Math.floor((midi-60)/12),pc=((midi%12)+12)%12;let note=0,d=12;for(let i=0;i<7;i++)if(Math.abs(pc-naturals[i])<d){d=Math.abs(pc-naturals[i]);note=i;}const y=base-(octave*7+note)*4;for(let line=top-8;line>=y;line-=8)markup+='<path d="M'+(x-6)+' '+line+'h12"/>';if(y>=base)markup+='<path d="M'+(x-6)+' '+base+'h12"/>';markup+='<ellipse cx="'+x+'" cy="'+y+'" rx="4" ry="2.9" fill="'+PART_COLORS[instrument]+'"/><path d="M'+(x+3)+' '+y+'v-18" class="tour-note-stem"/>';}
    }markup+='<path d="M'+(120+(beat-first)*29)+' 8V189" class="tour-score-playhead"/></svg>';sheet.innerHTML=markup;}
  function update(){const touring=rig.mode==='tour';if(wasTour&&!touring){stop(rig.tour.time>=rig.tour.duration-.02);wasTour=false;if(!active)return;}wasTour=touring;if(!active||(!touring&&!cameraEnded))return;if(cameraEnded&&(model.ended||!model.motor)){active=false;player.stop();return;}const time=rig.tour.time;
    if(time>=TOUR_ENTRANCES['guitar-0'])guitar=true;if(time>=TOUR_ENTRANCES.keyboard)keys=true;
    const presenting=touring&&time>=16&&time<27;if(presenting)guitarPresentation.select(0);else if(guitarPresentation.selected===0)guitarPresentation.release();env.setConcert(touring&&time>=26&&time<36);breeze.setClosed(touring&&time>=26&&time<36);
    const now=audio.ctx.currentTime,seconds=60/project.bpm,elapsed=model.transport;
    if(model.audible){let guard=0;const span=project.bars*4*seconds;if(scoreRevision!==model.transportRevision){scoreRevision=model.transportRevision;cycle=Math.floor(elapsed/span);index=0;}while(guard++<1024){if(index>=events.length){index=0;cycle++;}const e=events[index],at=(e.beat+cycle*project.bars*4)*seconds;if(at>=elapsed+.65||at>=model.duration)break;index++;if(at<elapsed-.07)continue;if((e.instrument==='keyboard'&&!keys)||(e.instrument==='guitar-0'&&!guitar))continue;player.index=index;player.cycle=cycle;player.schedule(e,now+(at-elapsed)/Math.max(.5,model.playbackRate),'score:tour');}}
    player.update();player.projection.update(events,now-elapsed,now,seconds,project.bars*4*seconds,true,touring&&keys&&time<48);sheet.hidden=!touring||time<48;if(!sheet.hidden)preview();
  }
  return{start,update,stop,get active(){return active;},get preparing(){return preparing;},get holdingGuitar(){return active&&rig.mode==='tour'&&rig.tour.time>=16&&rig.tour.time<27;},get state(){return{active,preparing,preparePhase,guitar,keyboard:keys,scheduled:index+cycle*events.length,cameraEnded,cycle,time:model.transport,original:true};},dispose(){stop();finale.remove();sheet.remove();}};
}
