import {RECORDS} from './audio.js';import {CHORDS,frequency} from './mechanics.js';import {albumArt} from './artwork.js';
const $=s=>document.querySelector(s);const names=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];
export function mountUI({model,audio,keyboard,guitars,deck,rig,guitarPresentation,toast}){let instrument=['turntable','keyboard','guitars'].includes(rig.mode)?rig.mode:null,guitarIndex=0,chord='C',octave=0,timbre='piano',metronome=null,bpm=86,record=RECORDS[0],side=0,loadingRecord=false,startingRecord=false,take=false,tourPreparing=false;const held=new Set();let timer=0;
 function panel(content){$('#panel').hidden=false;$('#panel').innerHTML='<button class="close" aria-label="Close instrument controls">×</button>'+content;$('#panel .close').onclick=()=>{$('#panel').hidden=true;canvasFocus();};}
 function canvasFocus(){$('#scene').focus({preventScroll:true});}
 function control(label,id,value,min,max,step,unit=''){return `<div class="control-row"><label for="${id}">${label}</label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"><output for="${id}">${value}${unit}</output></div>`;}
 function range(id,fn,unit=''){const e=$('#'+id);if(!e)return;e.oninput=()=>{const v=Number(e.value);e.nextElementSibling.textContent=(Math.round(v*100)/100)+unit;fn(v);};}
 async function ensureAudio(){await audio.resume();$('#sound-toggle').textContent=audio.muted?'♩':'♫';$('#sound-toggle').setAttribute('aria-label',audio.muted?'Unmute studio audio':'Mute studio audio');}
 async function play(){if(startingRecord)return;startingRecord=true;$('#play-button').disabled=true;try{await ensureAudio();if(model.motor){model.stop();toast('Motor off · the platter is braking.');}else{if(!audio.loadedRecord)toast('Preparing the record…');await audio.ensureRecord();model.start();if(model.arm!=='groove'){model.setCue(true);await new Promise(resolve=>{const t=setInterval(()=>{if(model.cue>.98){clearInterval(t);resolve();}},40);});model.placeArm();await new Promise(resolve=>setTimeout(resolve,450));}model.setCue(false);toast('Direct drive on · lowering the stylus.');}}catch(e){toast(e.message);}finally{startingRecord=false;$('#play-button').disabled=false;}}
 function openDeck(){instrument='turntable';panel(`<small>AFTERLIGHT / DD–01</small><h2>The listening corner</h2><p>Quartz direct drive. A real 12-inch disc, a 230 mm tonearm, and a little time to slow down.</p><div class="stat-grid"><div><small>ACTUAL SPEED</small><strong id="actual-rpm">0.000 RPM</strong></div><div><small>STYLUS RADIUS</small><strong id="groove-radius">146.0 mm</strong></div><div><small>NEEDLE</small><strong id="cue-state">Lifted</strong></div><div><small>MEDIA RATE</small><strong id="media-rate">0.000×</strong></div></div><div class="button-row"><button id="motor">Motor</button><button id="cue">Cue lever</button><button id="arm">Set arm</button></div><div class="button-row"><button id="park">Park arm</button><button id="lid">Dust cover</button><button id="flip">Flip side</button></div><div class="button-row"><button data-rpm="33.333333">33⅓</button><button data-rpm="45">45</button><button data-rpm="78">78</button></div>${control('Pitch','pitch',model.pitch,-8,8,.1,'%')}${control('Tracking force','force',model.trackingForce,0,4,.1,'g')}${control('Anti-skate','skate',model.antiskate,0,4,.1)}${control('Volume','volume',audio.volume,0,1,.01)}<div class="control-row"><label for="brake">Electronic brake</label><input type="checkbox" id="brake" ${model.brake?'checked':''}></div><p class="view-note">Click or drag the record to scratch. Lift the cue to reposition the stylus. RPM and pitch change the actual audio speed and key; lifting the needle silences the groove.</p><h3>Your own recording</h3><p>Place a local audio file on the deck. It stays on this device.</p><input type="file" id="audio-file" accept="audio/*" aria-label="Import local audio"><button class="full-button" id="collection">Browse the record shelf</button>`);
  $('#motor').onclick=async()=>{await ensureAudio();model.power=true;if(model.motor)model.stop();else model.start();};$('#cue').onclick=()=>model.setCue(!model.cueTarget);$('#arm').onclick=()=>{toast(model.placeArm()?'Tonearm positioned over the lead-in.':'Lift the cue before moving the tonearm.');};$('#park').onclick=()=>model.returnArm();$('#lid').onclick=()=>deck.toggleLid();$('#flip').onclick=()=>changeRecord(record,1-side);$('#brake').onchange=e=>model.brake=e.target.checked;$('#collection').onclick=openLibrary;
  range('pitch',v=>model.pitch=v,'%');range('force',v=>model.trackingForce=v,'g');range('skate',v=>model.antiskate=v);range('volume',v=>audio.setVolume(v));bindSpeeds();
  $('#audio-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{await parkForChange();const duration=await audio.importFile(file);model.load(duration);record={...RECORDS[0],id:'custom',title:file.name.replace(/\.[^.]+$/,''),subtitle:'Your own recording',duration,key:'Custom audio'};deck.setArtwork(record,0);updateTrack();toast('Your recording is on the platter. Press play.');}catch(err){toast(err.message);}};
 }
 function bindSpeeds(){document.querySelectorAll('[data-rpm]').forEach(b=>{b.classList.toggle('selected',Math.abs(Number(b.dataset.rpm)-model.rpm)<.001);b.onclick=()=>{model.setSpeed(Number(b.dataset.rpm));bindSpeeds();};});}
 async function parkForChange(){model.returnArm();model.stop();model.power=true;toast('Lifting the stylus and braking before changing records…');await new Promise(resolve=>{const id=setInterval(()=>{if(model.cue>.99&&Math.abs(model.actualRPM)<.15){clearInterval(id);resolve();}},80);});}
 async function changeRecord(next,nextSide=0){if(loadingRecord)return;loadingRecord=true;try{await ensureAudio();await parkForChange();if(!model.load(next.duration))throw Error('Wait for the platter to stop and the stylus to lift.');record=next;side=nextSide;await audio.loadRecord(next,side);deck.setArtwork(record,side);updateTrack();toast(next.title+' · side '+(side?'B':'A')+' is ready.');return true;}catch(e){toast(e.message);}finally{loadingRecord=false;}}
 function updateTrack(){$('#track-title').textContent=record.title+', side '+(side?'B':'A');$('#track-detail').textContent='Yua · '+record.subtitle;$('#duration').textContent=time(record.duration);$('#album-mini').style.backgroundImage=`url(${albumArt(record).image.toDataURL()})`;$('#album-mini').style.backgroundSize='cover';$('#album-mini').innerHTML='';}
 function openLibrary(){instrument='records';panel(`<small>YUA’S COLLECTION</small><h2>Songs to stay for</h2><p>A shelf of little worlds. Choose a sleeve to place it on the turntable.</p>${RECORDS.map(r=>`<button class="record-card" data-record="${r.id}"><div class="art" style="background-image:url(${albumArt(r).image.toDataURL()})"></div><div><strong>${r.title}</strong><span>${r.description}</span><i>${r.key.toUpperCase()} · ${r.bpm} BPM · ${time(r.duration)}</i></div></button>`).join('')}<p class="view-note" style="margin-top:16px">Original procedural home-session instrumentals. Every cover was drawn from scratch in code; no generated or downloaded art.</p>`);document.querySelectorAll('[data-record]').forEach(b=>b.onclick=()=>changeRecord(RECORDS.find(r=>r.id===b.dataset.record)));}
 function openKeys(){instrument='keyboard';panel(`<small>AFTERLIGHT / STUDIO 88</small><h2>A song starts here</h2><p>88 individually moving keys. Velocity-sensitive struck-string synthesis, concert A = 440 Hz.</p><div class="key-readout" id="key-name">C major</div><div class="keyboard-screen"><span id="frequency-readout">Press a key</span><span id="sustain-readout">Sustain off</span></div><div class="control-row"><label for="voice">Voice</label><select id="voice"><option value="piano">Studio grand</option><option value="ep">Electric piano</option></select></div><div class="button-row"><button id="oct-down">Octave −</button><button id="oct-up">Octave +</button><button id="sustain">Sustain</button></div><div class="button-row"><button id="reference">A / 440 Hz</button><button id="metro">Metronome</button></div>${control('Tempo','tempo',bpm,40,180,1,' BPM')}${control('Volume','key-volume',audio.volume,0,1,.01)}<button data-score="keyboard" class="full-button">▤ Perform a music book</button><button id="take" class="full-button ${take?'active-take':''}">${take?'■ Stop & save recording':'● Record a take'}</button><p class="view-note">Play with <span class="kbd">A W S E D F T G Y H U J K</span>.<br><span class="kbd">Z / X</span> octave · <span class="kbd">Shift</span> damper pedal.<br>Click keys near the front for a stronger strike. Recordings capture studio audio locally; no microphone permission is needed.</p>`);
  $('#voice').value=timbre;$('#voice').onchange=e=>timbre=e.target.value;$('#oct-down').onclick=()=>setOctave(-1);$('#oct-up').onclick=()=>setOctave(1);$('#sustain').onclick=()=>setSustain(!audio.sustain);$('#reference').onclick=async()=>{await ensureAudio();startNote(69,.65);setTimeout(()=>endNote(69),1000);};$('#metro').onclick=toggleMetro;range('tempo',v=>{bpm=v;if(metronome){clearInterval(metronome);metronome=null;toggleMetro();}},' BPM');range('key-volume',v=>audio.setVolume(v));$('#take').onclick=recordTake;
 }
 function setOctave(d){octave=Math.max(-2,Math.min(2,octave+d));toast('Computer keyboard octave: C'+(4+octave));}
 async function toggleMetro(){await ensureAudio();if(metronome){clearInterval(metronome);metronome=null;toast('Metronome off');return;}let n=0;const tick=()=>{const c=audio.ctx,o=c.createOscillator(),g=c.createGain();o.frequency.value=n++%4===0?1350:950;g.gain.setValueAtTime(.075,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.04);o.connect(g);g.connect(audio.master);o.start();o.stop(c.currentTime+.05);};tick();metronome=setInterval(tick,60000/bpm);toast('Metronome · '+bpm+' BPM');}
 async function recordTake(){await ensureAudio();take=!take;const button=$('#take');if(take){audio.beginTake();audio.chunks=[];audio.capture=new MediaRecorder(audio.recordDestination.stream);audio.capture.ondataavailable=e=>audio.chunks.push(e.data);audio.capture.start();if(button){button.textContent='■ Stop & save recording';button.classList.add('active-take');}toast('Recording your take…');}else{const notes=audio.endTake();const capture=audio.capture;capture.onstop=()=>{download(new Blob(audio.chunks,{type:capture.mimeType}),'yua-home-session.webm');download(new Blob([JSON.stringify(notes,null,2)],{type:'application/json'}),'yua-home-session.notes.json');toast('Audio take and note performance saved.');};capture.stop();if(button){button.textContent='● Record a take';button.classList.remove('active-take');}}}
 function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
 function openGuitars(index=guitarIndex){instrument='guitars';guitarIndex=index;guitarPresentation.select(index);const g=guitars[index];panel(`<small>THE GUITAR WALL</small><h2>Six strings, a feeling</h2><div class="control-row"><label for="guitar-select">Instrument</label><select id="guitar-select">${guitars.map((g,i)=>`<option value="${i}">${g.name}</option>`).join('')}</select></div><p>Click a string to pluck it. Choose a voicing, or fret the neck directly. Standard E–A–D–G–B–E tuning.</p><div class="guitar-strings">${['E₂','A₂','D₃','G₃','B₃','E₄'].map((s,i)=>`<button data-string="${i}">${s}</button>`).join('')}</div><div class="chord-grid button-row">${Object.keys(CHORDS).map(c=>`<button data-chord="${c}" class="${c===chord?'chosen':''}">${c}</button>`).join('')}</div><div class="button-row"><button id="strum-down">↓ Downstroke</button><button id="strum-up">↑ Upstroke</button></div><button data-score="guitars" class="full-button">▤ Perform a music book</button><h3>Individual string tuning</h3>${g.detunes.map((v,i)=>control(['Low E','A','D','G','B','High E'][i],'tuning-'+i,v,-100,100,1,'¢')).join('')}<p class="view-note">Karplus–Strong vibrating-string synthesis with body resonance. Frets follow 12-TET and string length; visible strings ring down after every pluck. <span class="kbd">Space</span> strums the selected chord.</p>`);$('#guitar-select').value=String(index);$('#guitar-select').onchange=e=>openGuitars(Number(e.target.value));document.querySelectorAll('[data-string]').forEach(b=>b.onclick=()=>pluck(Number(b.dataset.string)));document.querySelectorAll('[data-chord]').forEach(b=>b.onclick=()=>{chord=b.dataset.chord;document.querySelectorAll('[data-chord]').forEach(b=>b.classList.toggle('chosen',b.dataset.chord===chord));strum();});$('#strum-down').onclick=()=>strum(1);$('#strum-up').onclick=()=>strum(-1);g.detunes.forEach((_,i)=>range('tuning-'+i,v=>g.detunes[i]=v,'¢'));
 }
 async function pluck(s,fret=0,index=guitarIndex){await ensureAudio();const g=guitars[index];g.vibrate(s,fret);audio.pluck(s,fret,.8,g.type,g.detunes[s]);}
 async function strum(dir=1){await ensureAudio();const g=guitars[guitarIndex];audio.strum(chord,g.type,g.detunes,dir);(dir>0?[0,1,2,3,4,5]:[5,4,3,2,1,0]).forEach((s,i)=>{if(CHORDS[chord][s]>=0)setTimeout(()=>g.vibrate(s,CHORDS[chord][s]),i*24);});}
 async function startNote(midi,velocity=.75){if(midi<21||midi>108)return;held.add(midi);keyboard.press(midi,velocity);await ensureAudio();audio.pianoOn(midi,velocity,timbre);if(!held.has(midi))setTimeout(()=>audio.pianoOff(midi),180);const name=names[midi%12]+(Math.floor(midi/12)-1);keyboard.setDisplay(name,audio.sustain);if($('#key-name'))$('#key-name').textContent=detectChord()||name;if($('#frequency-readout'))$('#frequency-readout').textContent=frequency(midi).toFixed(2)+' Hz';}
 function endNote(midi){held.delete(midi);keyboard.release(midi);audio.pianoOff(midi);}
 function detectChord(){const pcs=[...new Set([...held].map(m=>m%12))];if(pcs.length<3)return null;for(const r of pcs){const p=pcs.map(v=>(v-r+12)%12);if([0,4,7].every(v=>p.includes(v)))return names[r]+' major';if([0,3,7].every(v=>p.includes(v)))return names[r]+' minor';}return null;}
 function setSustain(v){audio.setSustain(v);keyboard.setDisplay('SUSTAIN',v);if($('#sustain-readout'))$('#sustain-readout').textContent=v?'Sustain on':'Sustain off';}
 function inspect(name,idx){rig.choose(name);if(name==='turntable')openDeck();else if(name==='keyboard')openKeys();else if(name==='guitars')openGuitars(idx);else{$('#panel').hidden=true;instrument=null;}canvasFocus();}
 const map={KeyA:0,KeyW:1,KeyS:2,KeyE:3,KeyD:4,KeyF:5,KeyT:6,KeyG:7,KeyY:8,KeyH:9,KeyU:10,KeyJ:11,KeyK:12,KeyO:13,KeyL:14,KeyP:15,Semicolon:16};const keyboardDown=new Map();
 window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||e.target.closest?.('#composer,#camera-play'))return;if(e.repeat)return;if(instrument==='keyboard'&&['keyboard','concert'].includes(rig.mode)){if(map[e.code]!==undefined){const m=60+octave*12+map[e.code];keyboardDown.set(e.code,m);startNote(m,.74);e.preventDefault();return;}if(e.code==='KeyZ'){setOctave(-1);return;}if(e.code==='KeyX'){setOctave(1);return;}if(e.code.startsWith('Shift')){setSustain(true);return;}}
  if(e.code==='Space'&&rig.mode==='tour'){e.preventDefault();rig.tour.togglePause();return;}if(e.code==='KeyF'&&rig.mode!=='keyboard'&&rig.mode!=='concert'){inspect('tour');return;}if(e.code==='Space'){e.preventDefault();if(instrument==='guitars'&&rig.mode==='guitars')strum();else play();}if(e.code==='KeyV')inspect(rig.mode==='room'?'sofa':'room');if(e.code==='KeyC')inspect('sofa');if(e.code==='Digit1')inspect('turntable');if(e.code==='Digit2')inspect('keyboard');if(e.code==='Digit3')inspect('guitars');if(e.code==='Digit4')openLibrary();if(e.code==='Escape'){$('#panel').hidden=true;audio.panic();for(const m of[...held])endNote(m);instrument=null;rig.choose('sofa');}if(e.code==='KeyH')document.body.classList.toggle('cinema');});
 window.addEventListener('keyup',e=>{if(keyboardDown.has(e.code)){endNote(keyboardDown.get(e.code));keyboardDown.delete(e.code);}if(e.code.startsWith('Shift')&&instrument==='keyboard')setSustain(false);});window.addEventListener('blur',()=>{for(const m of[...held])endNote(m);audio.panic();});
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>inspect(b.dataset.view));$('#deck-button').onclick=()=>inspect('turntable');$('#library-button').onclick=openLibrary;$('#album-mini').onclick=openLibrary;$('#play-button').onclick=play;$('#seek').onchange=async e=>{const p=Number(e.target.value),resume=model.cueTarget===0;model.setCue(true);await new Promise(resolve=>{const t=setInterval(()=>{if(model.cue>.99){clearInterval(t);resolve();}},40);});model.seek(p);model.placeArm();setTimeout(()=>{if(resume)model.setCue(false);},750);toast('Cueing to the selected groove.');};$('#sound-toggle').onclick=async()=>{try{if(!audio.ready||audio.ctx?.state!=='running'){await ensureAudio();toast('Studio sound enabled.');}else{audio.setMute(!audio.muted);toast(audio.muted?'Studio muted':'Studio sound on');}$('#sound-toggle').textContent=audio.muted?'♩':'♫';$('#sound-toggle').setAttribute('aria-label',audio.muted?'Unmute studio audio':'Mute studio audio');$('#sound-toggle').title=audio.muted?'Unmute studio audio':'Mute studio audio';}catch(e){toast(e.message);}};
 $('#help-button').onclick=()=>panel(`<small>MAKE YOURSELF AT HOME</small><h2>Room controls</h2><div class="note-list"><span class="kbd">Drag</span> Look around while sitting or walking.<br><span class="kbd">W A S D</span> Stand and walk, with furniture collision.<br><span class="kbd">E</span> Interact with what you’re looking at.<br><span class="kbd">C</span> Sit back on the sofa.<br><span class="kbd">V</span> Switch to the cutaway overview.<br><span class="kbd">1 / 2 / 3</span> Inspect deck, keys, guitars.<br><span class="kbd">4</span> Browse the record collection.<br><span class="kbd">Space</span> Start/stop record or strum guitar.<br><span class="kbd">F</span> Cinematic room tour (Space pauses the camera).<br><span class="kbd">H</span> Clean cinematic frame.<br><span class="kbd">Esc</span> Leave instrument and return to sofa.</div><h3>About this build</h3><p>Original geometry, wear, artwork and music created from scratch in code. TSL materials use WebGPU with automatic WebGL2 fallback. Internal synthesis is physically informed, not a recording of a commercial instrument.</p><button class="full-button" id="switch-backend">Reload with ${location.search.includes('webgl')?'WebGPU auto':'WebGL2'} backend</button>`);$('#help-button').addEventListener('click',()=>{$('#switch-backend').onclick=()=>location.href=location.search.includes('webgl')?'/':'/?webgl';});
 $('#tour-stop').onclick=()=>inspect('sofa');$('#tour-pause').onclick=()=>rig.tour.togglePause();
 if(rig.mode==='guitars')guitarPresentation.select(guitarIndex);bindSpeeds();updateTrack();
 function time(s){return Math.floor(s/60)+':'+String(Math.floor(s%60)).padStart(2,'0');}
 return{inspect,play,setTourPreparing(value){tourPreparing=value;$('#tour-pause').disabled=value;},setInstrument(name){instrument=name;},prepareTourRecord:()=>changeRecord(RECORDS[0],0),startNote,endNote,pluck,openLibrary,openDeck,setSustain,get instrument(){return instrument;},action(action,data={}){if(action==='key')startNote(data.midi,data.velocity??.75);else if(action==='pluck')pluck(data.string,data.fret||0,data.guitar||0);else if(action==='sustain')setSustain(!audio.sustain);else if(action==='cue')model.setCue(!model.cueTarget);else if(action==='arm'){model.arm==='rest'?model.placeArm():model.returnArm();}else if(action==='motor'||action==='power')play();else if(action==='lid')deck.toggleLid();else if(action==='rpm33'){model.setSpeed(33+1/3);bindSpeeds();}else if(action==='rpm45'){model.setSpeed(45);bindSpeeds();}else if(action==='records')openLibrary();},update(dt){const touring=rig.mode==='tour';$('#tour-hud').hidden=!touring;if(touring){const s=rig.tour.state;$('#tour-title').textContent=s.name;$('#tour-detail').textContent=s.detail;$('#tour-progress').value=s.progress;$('#tour-pause').textContent=tourPreparing?'Pause':s.paused?'Resume':'Pause';}timer+=dt;if(timer<.1)return;timer=0;$('#elapsed').textContent=time(model.transport);$('#seek').value=model.transport/model.duration;$('#play-button').textContent=model.motor?'Ⅱ':'▶';$('#play-state').textContent=model.audible?'GROOVE TRACKING':model.motor?'STYLUS LIFTED':model.actualRPM>.2?'BRAKING':'READY';if($('#actual-rpm'))$('#actual-rpm').textContent=model.actualRPM.toFixed(3)+' RPM';if($('#groove-radius'))$('#groove-radius').textContent=(model.grooveRadius*1000).toFixed(1)+' mm';if($('#cue-state'))$('#cue-state').textContent=model.arm==='rest'?'Parked':model.cue>.02?'Lifted':'Tracking';if($('#media-rate'))$('#media-rate').textContent=model.playbackRate.toFixed(3)+'×';}}
}
