import {hasPerf} from './runtime-performance.js';
import {THREE,box,rod,torus} from './geometry.js';import {mat,palette as P} from './materials.js';import {CurtainCloth} from './cloth.js';import {color,uv,sin,float,mix} from 'three/tsl';
export function openWindow(room){const root=room.root,cloths=[],meshes=[],rings=[];let angle=.62,target=.62,closed=0,closedTarget=0;const pane=new THREE.Group();pane.position.set(-4.065,2.63,1.256);root.add(pane);pane.userData.action='window';
 const glass=new THREE.MeshPhysicalNodeMaterial({color:'#d6e8e5',metalness:.15,roughness:.12,transparent:true,opacity:.12,side:THREE.DoubleSide,depthWrite:false});box(pane,[.006,1.59,1.275],[0,0,-.637],glass,.001);
 for(const z of[0,-1.275])box(pane,[.047,1.67,.037],[0,0,z],P.cream,.004);for(const y of[-.817,.817])box(pane,[.045,.037,1.31],[0,y,-.637],P.cream,.004);rod(pane,[.033,-.17,-1.22],[.033,.02,-1.22],.011,P.brass);
 const linen=new THREE.MeshPhysicalNodeMaterial({color:'#e9dac5',roughness:.95,transparent:true,opacity:.52,side:THREE.DoubleSide,depthWrite:false,sheen:.7,sheenColor:'#e4bfa7'});const threads=sin(uv().x.mul(1300)).mul(sin(uv().y.mul(1700))).mul(.055).add(.50);linen.opacityNode=threads;linen.colorNode=color('#eedbc1').mul(mix(float(.95),float(1),sin(uv().x.mul(260)).mul(.5).add(.5)));
 for(const [edge,seed]of[[-2.61,0],[.69,3]]){const cloth=new CurtainCloth({edge,width:.55,seed,cols:31,rows:28,materialWidth:1.96}),g=new THREE.BufferGeometry(),coords=new Float32Array(cloth.count*2),indices=[];g.setAttribute('position',new THREE.BufferAttribute(cloth.p,3));for(let y=0;y<cloth.rows;y++)for(let c=0;c<cloth.cols;c++){const i=y*cloth.cols+c;coords[i*2]=c/(cloth.cols-1);coords[i*2+1]=y/(cloth.rows-1);if(c+1<cloth.cols&&y+1<cloth.rows){const a=i,b=i+1,d=i+cloth.cols,e=d+1;indices.push(a,d,b,b,d,e);}}
  g.setAttribute('uv',new THREE.BufferAttribute(coords,2));g.setIndex(indices);g.computeVertexNormals();const m=new THREE.Mesh(g,linen);m.userData.dynamic=true;m.frustumCulled=false;m.castShadow=false;m.receiveShadow=true;root.add(m);cloths.push(cloth);meshes.push(m);const panelRings=[];for(let i=0;i<8;i++){const r=torus(root,.018,.002,[-3.96,3.56,edge+i*.075],P.brass,[Math.PI/2,0,0]);r.userData.dynamic=true;panelRings.push(r);}rings.push(panelRings);
 }
 let accumulator=0,worker=null,inFlight=false,world=null,dynamicClock=0,positionsDirty=true,frozen=false,deferred=null;const applyPositions=m=>{m.positions.forEach((p,i)=>{for(let n=0;n<p.length;n++)cloths[i].p[n]=p[n]/world.scale;});positionsDirty=true;};return{setFrozen(value){frozen=value;if(!value&&deferred){applyPositions(deferred);deferred=null;}},dispose(){worker?.terminate();},useWorker(collision){world=collision;worker=new Worker(new URL('./cloth-worker.js',import.meta.url),{type:'module'});worker.onmessage=({data:m})=>{if(frozen)deferred=m;else applyPositions(m);inFlight=false;};worker.postMessage({type:'init',scale:world.scale,solids:world.serializeClothSolids(),parameters:[{edge:-2.61*.75,width:.55*.75,materialWidth:1.96*.75,cols:31,rows:28,x:-3.96*.75,top:3.48*.75,height:2.64*.75,pleat:.035*.75},{edge:.69*.75,width:.55*.75,materialWidth:1.96*.75,cols:31,rows:28,x:-3.96*.75,top:3.48*.75,height:2.64*.75,pleat:.035*.75,seed:3}]});inFlight=true;},cloths,pane,setClosed(value){closedTarget=value?1:0;},get curtainClosed(){return closed;},get open(){return target>0;},toggle(){target=target?0:.62;},update(dt){if(frozen)return;angle+=(target-angle)*(1-Math.exp(-dt*3));pane.rotation.y=angle;closed+=(closedTarget-closed)*(1-Math.exp(-dt*1.7));const width=.55+(1.96-.55)*closed,edges=[-2.66,.69-(.69+.70)*closed];cloths.forEach((c,i)=>c.setCoverage(width,edges[i]));rings.forEach((list,i)=>list.forEach((r,j)=>r.position.z=edges[i]+width*j/7));accumulator+=dt;if(worker){dynamicClock+=dt;if(!inFlight&&accumulator>=1/60){worker.postMessage({type:'step',dt:Math.min(.066,accumulator),wind:.65*Math.sin(angle)/Math.sin(.62)*(1-closed*.85),coverage:edges.map(edge=>({width:width*world.scale,edge:edge*world.scale})),dynamic:dynamicClock>1/30?world.serializeClothSolids(true):undefined});if(dynamicClock>1/30)dynamicClock=0;accumulator=0;inFlight=true;}}else while(accumulator>=1/60){cloths.forEach(c=>{c.wind=.65*Math.sin(angle)/Math.sin(.62)*(1-closed*.85);c.step(1/60);});accumulator-=1/60;positionsDirty=true;}if(!hasPerf('cloth_dirty')||positionsDirty)meshes.forEach(m=>{m.geometry.attributes.position.needsUpdate=true;m.geometry.computeVertexNormals();});positionsDirty=false;}};
}
