import json,copy
from pathlib import Path
p=Path('progress/cat-reference/character-sculpt-spec.json');s=json.loads(p.read_text());a=json.loads(Path('progress/cat-reference/assessment.json').read_text());s['preSpecAssessment']=a['preSpecAssessment'];s['qualityContract']=a['qualityContract'];base=s['componentTree'][0]
rows=[('root','WindowCat','macro',None,'hidden','assembled-solid','box',[0,0,0],[1,1,1]),('body','ContinuousRiggedFeline','macro','root','fur','continuous-sculpt','implicit-surface',[0,0,0],[.30,.45,.70]),('head','ContinuousFelineSkull','macro','body','fur','continuous-sculpt','implicit-surface',[.015,.035,.245],[.37,.28,.28]),('tail','ThickCurledTail','macro','body','fur','continuous-sculpt','curve-sweep',[-.026,-.017,-.313],[.20,.47,.28]),('ear-left','LeftEar','meso','head','ear','continuous-sculpt','curve-sweep',[-.094,.086,-.005],[.14,.15,.042]),('ear-right','RightEar','meso','head','ear','continuous-sculpt','curve-sweep',[.094,.086,-.005],[.14,.15,.042]),('eye-left','LeftEye','meso','head','line','material-only','plane-card',[-.074,-.018,.116],[.07,.035,.002]),('eye-right','RightEye','meso','head','line','material-only','plane-card',[.074,-.018,.116],[.07,.035,.002]),('jaw','HingedLowerJaw','meso','head','fur','continuous-sculpt','implicit-surface',[0,-.074,.047],[.085,.043,.078]),('mouth','RecessedMouthInterior','meso','head','oral','continuous-sculpt','curve-sweep',[0,-.085,.093],[.073,.042,.01]),('nose','SmallTriangularNose','meso','head','pink','surface-relief','extrude',[0,-.060,.130],[.012,.008,.001]),('tongue','TongueInsideJaw','meso','jaw','pink','continuous-sculpt','curve-sweep',[0,-.002,.040],[.03,.008,.048]),('whiskers','Whiskers','meso','head','line','fiber-strand','tube',[0,-.059,.125],[.27,.04,.02]),('smile','ClosedMouthLine','micro','head','line','fiber-strand','tube',[0,-.082,.134],[.039,.010,.01]),('toes','ToeCreases','micro','body','line','fiber-strand','tube',[0,.033,.228],[.024,.008,.01]),('cheek-blush','CheekBlush','micro','head','fur','material-only','plane-card',[0,-.047,.114],[.24,.056,.01]),('tooth-left','UpperCanineLeft','micro','head','fur','assembled-solid','cone',[-.024,-.083,.122],[.005,.01,.005]),('tooth-right','UpperCanineRight','micro','head','fur','assembled-solid','cone',[.024,-.083,.122],[.005,.01,.005])]
cs=[]
for id,name,level,parent,material,top,primitive,pos,dims in rows:
 c=copy.deepcopy(base);c.update(id=id,name=name,level=level,parent=parent,material=material,materialLayers=[material],primitive=primitive,topologyClass=top,topologyRationale='Feline reference '+name+'; '+top+' topology, not a generic humanoid primitive',confidence=.9 if id!='body' else .65)
 c['dimensions']={'width':dims[0],'height':dims[1],'depth':dims[2],'units':'meters-before-room-scale-0.75','confidence':.65};c['transform']={'position':pos,'rotation':[0,0,0],'scale':[1,1,1]};c['actionProfile']['animationRole']='root' if not parent else 'static';c['actionProfile']['collider']['type']='compound' if id=='body' else 'ellipsoid';c['actionProfile']['destruction'].update(breakable=False,fractureGroup=id,detachableFragments=[]);c['actionProfile']['sockets']=[{'id':name+'Socket','position':[0,0,0]}];c['evidenceRefs']=['user-cat-reference.png','analysis.md'];c['geometryDescriptor']['topologyIntent']=top;c['geometryDescriptor']['normalStrategy']='field-gradient / analytic swept normals';c['geometryDescriptor']['uvStrategy']='generated planar patch / arc-length sweep';c['localFeatures']=[];c['primaryGeometryLayer']='L0' if id in ['body','head','jaw'] else 'L1' if id in ['tail','ear-left','ear-right'] else 'L5' if top=='material-only' else 'L3'
 if parent:
  c['attachment']={'parentId':parent,'parentSocket':name+'Socket','localStart':pos,'localEnd':[pos[0],pos[1]+dims[1]*.7,pos[2]],'contactType':'surface-contact' if top in ['material-only','fiber-strand','surface-relief'] else 'embedded','baseRadius':dims[0]*.25,'endRadius':.002,'embedDepth':.026 if id.startswith('ear') else .022,'overlap':.026,'gapTolerance':.001,'evidenceRefs':['user-cat-reference.png','analysis.md']}
 cs.append(c)
# A leg is a deformation region of the continuous skin, not a physically detached skin mesh.
for d in a['preSpecAssessment']['detailInventory']['details']:
 target=d['mapsTo']['ref'].split('.')[0];target={'ear-left':'ear-left','eyes':'eye-left'}.get(target,target)
 d['mapsTo']['ref']=target+'.'+d['id'];next(c for c in cs if c['id']==target)['localFeatures'].append({'id':d['id'],'name':d['description'],'kind':d['kind'],'evidenceRefs':['user-cat-reference.png'],'confidence':d['confidence'],'geometryEffect':'bounded smooth implicit silhouette' if d['kind']=='contour' else 'none','materialEffect':'authored local color/line mask'})
s['componentTree']=cs
mats=[];mt=s['materials'][0]
for id,color in [('hidden','#000000'),('fur','#fcf6ec'),('ear','#dab398'),('pink','#cf9690'),('line','#935644'),('oral','#754b4e')]:
 m=copy.deepcopy(mt);m.update(id=id,name=id,color=color,baseColor=color,shaderModel='ToonLab 0.5.0 public TSL anime shader',notes='Stylized illustration: measured PBR unavailable; matte fur masses no noise bump.');m['albedo']={'dominant':color,'secondary':['#b68d80','#efd2bb'] if id=='fur' else [color],'samplingNotes':'Visible illustration palette; shading excluded from exact albedo claim'};m['colorVariation'].update(palette=m['albedo']['secondary']+[color],pattern='anatomical coat masks' if id=='fur' else 'flat',amplitude=.08,heightCorrelation=0);m['roughness']={'base':.87,'variation':.03,'map':'independent inferred matte response','localResponse':'non-measured, controlled stylized response'};m['normal']={'pattern':'none','strength':0,'scale':1,'space':'tangent'};m['surfaceFrequencyBands']=[{'id':'macro','frequency':2,'amplitude':.08,'role':'coat patches'},{'id':'meso','frequency':10,'amplitude':0,'role':'geometry carries cheek/paw masses'},{'id':'micro','frequency':50,'amplitude':0,'role':'deliberately no noisy fur normals in clean anime style'}];m['localOverrides']=[{'id':'anatomical-palette','region':'coat/ear/face','color':color,'roughness':.87,'confidence':.7,'evidenceRefs':['user-cat-reference.png']}];m['referencePbr']={'usable':False,'reason':'2D illustration with arbitrary painted shadows does not determine PBR maps; no maps asserted.'};mats.append(m)
s['materials']=mats;s['repetitionSystems']=[{'id':'whisker-pairs','componentRef':'whiskers','count':6,'distribution':'three per cheek, asymmetric tiny rake','seed':7719,'evidenceRefs':['user-cat-reference.png']},{'id':'toe-creases','componentRef':'toes','count':8,'distribution':'two per terminal paw bone','seed':7719,'evidenceRefs':['user-cat-reference.png']}]
refs=[c['id'] for c in cs]
s['buildPasses']=[{'id':id,'goal':goal,'componentRefs':refs,'acceptance':[goal]} for id,goal in [('blockout','Reference-like broad head, compressed torso/paws, attached ears and large upward tail in neutral map-stripped view.'),('structural-pass','Continuous head/skinned torso, ear depth below skull zero surface, head/jaw/tail sockets and finite rig.'),('form-refinement','Short muzzle, rounded cheeks/paws, tapered soft triangular ears, thick curved tail hold across views.'),('material-pass','Cream/tan/rose-brown reference palette and small warm linework on neutral, grazing and reference-like views.'),('lighting-pass','Real room lights do not wash out identity or force emissive cat surfaces.'),('interaction-pass','Four-beat planted walk, gravity-based jumps, compression/settling and camera glances without floating attachments.'),('optimization-pass','Conservative animated bounds, finite runtime and performance evidence, no parity claim without backend captures.')]]
s['featureReviewTargets']=[{'id':id,'name':name,'tier':'critical','passIds':passes,'minimumScore':.75,'mustPass':True,'componentRefs':comp,'evidenceRefs':['user-cat-reference.png']} for id,name,passes,comp in [('anatomy-proportion','Broad chibi head and compact paws',['blockout','form-refinement'],['body','head']),('pose-silhouette','Oversized upward curled tail',['blockout','form-refinement'],['tail']),('attachment-system','Physically embedded ears/head/tail',['structural-pass','form-refinement'],['head','ear-left','ear-right','tail']),('face-landmark-placement','Tiny sleepy eyes, short muzzle and smile',['material-pass'],['head','eye-left','eye-right','smile']),('outfit-and-palette','Cream tan rose-brown coat regions',['material-pass','lighting-pass'],['head','body','tail'])]]
s['referenceCamera'].update(solved=False,fovDegrees=35,positionHint=[.8,.65,1.7],note='Manual reference-like camera, matching original three-quarter angle; illustration perspective not exactly recoverable.')
s['suitability']={'verdict':'conditional','reason':'Stylized feline motion-capable interpretation, original hidden anatomy inferred.'};s['rig']={'enabled':True,'rootBone':'CatSpine','modelSpace':True,'source':'procedurally authored feline four chains; not humanoid template','bones':[]};s['assumptions']=['No photo projection: source pixels never used as rendered assets; user from-scratch requirement.','Generated unseen sides are proposals, not authoritative reference.','No measured PBR, no strand grooming, no exact likeness claim.'];s['performanceBudget']['targetTriangles']=100000;s['sculptPipeline']['currentPass']='blockout'
p.write_text(json.dumps(s,indent=2)+'\n')
